export const DEFAULT_WEBSOCKET_MAX_FAILS = 7;
export const DEFAULT_WEBSOCKET_MIN_RETRY_TIME = 3000; // 3 sec
export const DEFAULT_WEBSOCKET_MAX_RETRY_TIME = 300000; // 5 mins
export const DEFAULT_WEBSOCKET_JITTER_RANGE = 2000; // 2 sec
export const DEFAULT_CLIENT_PING_INTERVAL = 30000; // 30 sec

export const CLIENT_PING_TIMEOUT_ERR_CODE = 4000;
export const CLIENT_SEQUENCE_MISMATCH_ERR_CODE = 4001;
