export const DEFAULT_MAX_RECONNECT_FAILS = 7;
export const DEFAULT_MIN_RECONNECT_TIME = 3000; // 3 sec
export const DEFAULT_MAX_RECONNECT_TIME = 300000; // 5 mins
export const DEFAULT_RECONNECT_JITTER_RANGE = 2000; // 2 sec
export const DEFAULT_PING_INTERVAL = 30000; // 30 sec

export const PING_TIMEOUT_ERROR_CODE = 4000;
export const SEQUENCE_MISMATCH_ERROR_CODE = 4001;
