"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.appCallResponseSchema = exports.appBindingSchema = exports.appFormSchema = exports.appFormFieldSchema = exports.appFormTextFieldSchema = exports.appFormStaticSelectFieldSchema = exports.appFormLookupResponseSchema = exports.appFormValuesSchema = exports.appFormDynamicSelectFieldSchema = exports.appFormUsersFieldSchema = exports.appFormChannelsFieldSchema = exports.appFormMarkdownFieldSchema = exports.appFormBooleanFieldSchema = exports.appFormFieldTextSubTypeSchema = exports.appFormFieldTypeSchema = exports.appFormResponseDataSchema = exports.productScopeSchema = exports.productIdentifierSchema = exports.appLocationSchema = exports.appCallRequestSchema = exports.appCallSchema = exports.appCallMetadataForClientSchema = exports.appContextSchema = exports.appExpandSchema = exports.appExpandLevelSchema = exports.appManifestSchema = exports.appRequestedLocationSchema = exports.appPermissionSchema = void 0;
// Generated by ts-to-zod
const zod_1 = require("zod");
const apps_1 = require("./apps");
exports.appPermissionSchema = zod_1.z.enum(apps_1.AppPermission);
exports.appRequestedLocationSchema = zod_1.z.enum(apps_1.AppRequestedLocation);
exports.appManifestSchema = zod_1.z.object({
    app_id: zod_1.z.string(),
    version: zod_1.z.string().optional(),
    homepage_url: zod_1.z.string().optional(),
    icon: zod_1.z.string().optional(),
    display_name: zod_1.z.string(),
    description: zod_1.z.string().optional(),
    requested_permissions: zod_1.z.array(exports.appPermissionSchema).optional(),
    requested_locations: zod_1.z.array(exports.appRequestedLocationSchema).optional()
});
exports.appExpandLevelSchema = zod_1.z.enum(apps_1.AppExpandLevel);
exports.appExpandSchema = zod_1.z.object({
    app: exports.appExpandLevelSchema.optional(),
    acting_user: exports.appExpandLevelSchema.optional(),
    acting_user_access_token: exports.appExpandLevelSchema.optional(),
    channel: exports.appExpandLevelSchema.optional(),
    config: exports.appExpandLevelSchema.optional(),
    mentioned: exports.appExpandLevelSchema.optional(),
    parent_post: exports.appExpandLevelSchema.optional(),
    post: exports.appExpandLevelSchema.optional(),
    root_post: exports.appExpandLevelSchema.optional(),
    team: exports.appExpandLevelSchema.optional(),
    user: exports.appExpandLevelSchema.optional(),
    locale: exports.appExpandLevelSchema.optional()
});
exports.appContextSchema = zod_1.z.object({
    app_id: zod_1.z.string(),
    location: zod_1.z.string().optional(),
    acting_user_id: zod_1.z.string().optional(),
    user_id: zod_1.z.string().optional(),
    channel_id: zod_1.z.string().optional(),
    team_id: zod_1.z.string().optional(),
    post_id: zod_1.z.string().optional(),
    root_id: zod_1.z.string().optional(),
    props: zod_1.z.any().optional(),
    user_agent: zod_1.z.string().optional(),
    track_as_submit: zod_1.z.boolean().optional()
});
exports.appCallMetadataForClientSchema = zod_1.z.object({
    bot_user_id: zod_1.z.string(),
    bot_username: zod_1.z.string()
});
exports.appCallSchema = zod_1.z.object({
    path: zod_1.z.string(),
    expand: exports.appExpandSchema.optional(),
    state: zod_1.z.any().optional()
});
exports.appCallRequestSchema = exports.appCallSchema.extend({
    context: exports.appContextSchema,
    values: zod_1.z.any().optional(),
    raw_command: zod_1.z.string().optional(),
    selected_field: zod_1.z.string().optional(),
    query: zod_1.z.string().optional()
});
exports.appLocationSchema = zod_1.z.enum(apps_1.AppLocation);
exports.productIdentifierSchema = zod_1.z.string().nullable();
exports.productScopeSchema = zod_1.z.union([
    exports.productIdentifierSchema,
    zod_1.z.array(exports.productIdentifierSchema)
]);
exports.appFormResponseDataSchema = zod_1.z.object({
    errors: zod_1.z.record(zod_1.z.string(), zod_1.z.string()).optional()
});
exports.appFormFieldTypeSchema = zod_1.z.enum(apps_1.AppFormFieldType);
exports.appFormFieldTextSubTypeSchema = zod_1.z.enum(apps_1.AppFormFieldTextSubType);
const multiselectSchema = zod_1.z.object({
    multiselect: zod_1.z
        .boolean()
        .optional()
        .describe("Whether a select field allows multiple values to be selected.")
});
const refreshSchema = zod_1.z.object({
    refresh: zod_1.z
        .boolean()
        .optional()
        .describe("Allows the form to be refreshed when the value of the field has changed.")
});
const lookupSchema = zod_1.z.object({
    lookup: exports.appCallSchema.describe("A call that returns a list of options for dynamic select fields.")
});
const textSubTypeSchema = zod_1.z.object({
    subtype: exports.appFormFieldTextSubTypeSchema
        .optional()
        .describe("The subtype of text field that will be shown.")
});
const appFormFieldBaseSchema = zod_1.z.object({
    type: exports.appFormFieldTypeSchema.describe("The type of the field."),
    name: zod_1.z
        .string()
        .describe("Key to use in the values field of the call.\nCannot include spaces or tabs."),
    label: zod_1.z
        .string()
        .optional()
        .describe("The label of the flag parameter; used with autocomplete.\nIgnored for positional parameters."),
    modal_label: zod_1.z
        .string()
        .optional()
        .describe("Label of the field in modal dialogs.\nDefaults to label if not defined."),
    description: zod_1.z
        .string()
        .optional()
        .describe("Short description of the field, displayed beneath the field in modal dialogs"),
    hint: zod_1.z
        .string()
        .optional()
        .describe("The hint text for the field; used with autocomplete."),
    value: zod_1.z.unknown().optional().describe("The field's default value."),
    is_required: zod_1.z
        .boolean()
        .optional()
        .describe("Whether the field has a mandatory value."),
    readonly: zod_1.z
        .boolean()
        .optional()
        .describe("Whether a field's value is read-only."),
    position: zod_1.z
        .number()
        .optional()
        .describe("The index of the positional argument.\nA value greater than zero indicates the position this field is in.\nA value of -1 indicates the last argument.")
});
exports.appFormBooleanFieldSchema = appFormFieldBaseSchema.extend({
    type: zod_1.z.literal(apps_1.AppFormFieldType.BOOLEAN)
});
exports.appFormMarkdownFieldSchema = appFormFieldBaseSchema.extend({
    type: zod_1.z.literal(apps_1.AppFormFieldType.MARKDOWN)
});
exports.appFormChannelsFieldSchema = appFormFieldBaseSchema
    .extend(multiselectSchema.shape)
    .extend(refreshSchema.shape)
    .extend({
    type: zod_1.z.literal(apps_1.AppFormFieldType.CHANNEL)
});
exports.appFormUsersFieldSchema = appFormFieldBaseSchema
    .extend(multiselectSchema.shape)
    .extend(refreshSchema.shape)
    .extend({
    type: zod_1.z.literal(apps_1.AppFormFieldType.USER)
});
exports.appFormDynamicSelectFieldSchema = appFormFieldBaseSchema
    .extend(multiselectSchema.shape)
    .extend(lookupSchema.shape)
    .extend(refreshSchema.shape)
    .extend({
    type: zod_1.z.literal(apps_1.AppFormFieldType.DYNAMIC_SELECT)
});
const optionSchema = zod_1.z.any();
const optionsSchema = zod_1.z.any();
const minMaxLentghSchema = zod_1.z.any();
exports.appFormValuesSchema = zod_1.z.record(zod_1.z.string(), zod_1.z.union([zod_1.z.string(), optionSchema, zod_1.z.boolean()]).nullable());
exports.appFormLookupResponseSchema = zod_1.z.object({
    items: zod_1.z.array(optionSchema)
});
exports.appFormStaticSelectFieldSchema = appFormFieldBaseSchema
    .extend(multiselectSchema.shape)
    .extend(optionsSchema.shape)
    .extend(refreshSchema.shape)
    .extend({
    type: zod_1.z.literal(apps_1.AppFormFieldType.STATIC_SELECT)
});
exports.appFormTextFieldSchema = appFormFieldBaseSchema
    .extend(textSubTypeSchema.shape)
    .extend(minMaxLentghSchema.shape)
    .extend({
    type: zod_1.z.literal(apps_1.AppFormFieldType.TEXT)
});
exports.appFormFieldSchema = zod_1.z.union([
    exports.appFormBooleanFieldSchema,
    exports.appFormChannelsFieldSchema,
    exports.appFormDynamicSelectFieldSchema,
    exports.appFormMarkdownFieldSchema,
    exports.appFormStaticSelectFieldSchema,
    exports.appFormUsersFieldSchema,
    exports.appFormTextFieldSchema
]);
exports.appFormSchema = zod_1.z.object({
    title: zod_1.z.string().optional(),
    header: zod_1.z.string().optional(),
    footer: zod_1.z.string().optional(),
    icon: zod_1.z.string().optional(),
    submit_buttons: zod_1.z.string().optional(),
    cancel_button: zod_1.z.boolean().optional(),
    submit_on_cancel: zod_1.z.boolean().optional(),
    fields: zod_1.z.array(exports.appFormFieldSchema).optional(),
    source: exports.appCallSchema.optional(),
    submit: exports.appCallSchema.optional(),
    depends_on: zod_1.z.array(zod_1.z.string()).optional()
});
exports.appBindingSchema = zod_1.z.lazy(() => zod_1.z.object({
    app_id: zod_1.z.string(),
    location: zod_1.z.union([exports.appLocationSchema, zod_1.z.string()]).optional(),
    supported_product_ids: exports.productScopeSchema.optional(),
    icon: zod_1.z.string().optional(),
    label: zod_1.z.string().optional(),
    hint: zod_1.z.string().optional(),
    description: zod_1.z.string().optional(),
    role_id: zod_1.z.string().optional(),
    depends_on_team: zod_1.z.boolean().optional(),
    depends_on_channel: zod_1.z.boolean().optional(),
    depends_on_user: zod_1.z.boolean().optional(),
    depends_on_post: zod_1.z.boolean().optional(),
    bindings: zod_1.z.array(exports.appBindingSchema).optional(),
    form: exports.appFormSchema.optional(),
    submit: exports.appCallSchema.optional()
}));
exports.appCallResponseSchema = zod_1.z.object({
    type: zod_1.z.string(),
    text: zod_1.z.string().optional(),
    data: zod_1.z.any().optional(),
    navigate_to_url: zod_1.z.string().optional(),
    use_external_browser: zod_1.z.boolean().optional(),
    call: exports.appCallSchema.optional(),
    form: exports.appFormSchema.optional(),
    app_metadata: exports.appCallMetadataForClientSchema.optional()
});
//# sourceMappingURL=apps.zod.js.map