"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.botPatchSchema = exports.botSchema = void 0;
// Generated by ts-to-zod
const zod_1 = require("zod");
exports.botSchema = zod_1.z.object({
    user_id: zod_1.z.string(),
    username: zod_1.z.string(),
    display_name: zod_1.z.string().optional(),
    description: zod_1.z.string().optional(),
    owner_id: zod_1.z.string(),
    create_at: zod_1.z.number(),
    update_at: zod_1.z.number(),
    delete_at: zod_1.z.number()
});
exports.botPatchSchema = zod_1.z.object({
    username: zod_1.z.string(),
    display_name: zod_1.z.string(),
    description: zod_1.z.string()
});
//# sourceMappingURL=bots.zod.js.map