"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.channelMembershipSchema = exports.channelBookmarkWithFileInfoSchema = exports.channelBookmarkSchema = exports.serverChannelSchema = exports.channelUnreadResponseSchema = exports.channelNotifyPropsResponseSchema = exports.channelStatsSchema = exports.channelViewResponseSchema = exports.channelMemberCountsByGroupSchema = exports.channelMemberCountByGroupSchema = exports.channelsWithTotalCountSchema = exports.channelWithTeamDataSchema = exports.channelModerationPatchSchema = exports.channelModerationSchema = exports.channelMessageCountSchema = exports.channelBookmarkPatchSchema = exports.channelBookmarkCreateSchema = exports.channelBookmarkCreateBaseSchema = exports.channelBookmarkCreateFileSchema = exports.channelBookmarkCreateLinkSchema = exports.channelBookmarkTypeSchema = exports.orderedChannelCategoriesSchema = exports.channelCategorySchema = exports.channelCategorySortingSchema = exports.channelCategoryTypeSchema = exports.channelSchema = exports.channelNotifyDesktopSoundSchema = exports.channelNotifySchema = exports.channelTypeSchema = void 0;
// Generated by ts-to-zod
const zod_1 = require("zod");
const channels_1 = require("./channels");
exports.channelTypeSchema = zod_1.z.enum(channels_1.ChannelType);
exports.channelNotifySchema = zod_1.z.enum(channels_1.ChannelNotify);
exports.channelNotifyDesktopSoundSchema = zod_1.z.enum(channels_1.ChannelNotifyDesktopSound);
exports.channelSchema = zod_1.z.object({
    id: zod_1.z.string(),
    create_at: zod_1.z.number(),
    update_at: zod_1.z.number(),
    delete_at: zod_1.z.number(),
    team_id: zod_1.z.string(),
    type: exports.channelTypeSchema,
    display_name: zod_1.z.string(),
    name: zod_1.z.string(),
    header: zod_1.z.string(),
    purpose: zod_1.z.string(),
    last_post_at: zod_1.z.number(),
    total_msg_count: zod_1.z.number(),
    extra_update_at: zod_1.z.number(),
    creator_id: zod_1.z.string(),
    scheme_id: zod_1.z.string().optional().nullable(),
    props: zod_1.z.record(zod_1.z.string(), zod_1.z.unknown()).optional().nullable(),
    group_constrained: zod_1.z.boolean().optional().nullable(),
    shared: zod_1.z.boolean().optional().nullable(),
    total_msg_count_root: zod_1.z.number(),
    policy_id: zod_1.z.string().nullable(),
    last_root_post_at: zod_1.z.number()
});
exports.channelCategoryTypeSchema = zod_1.z.enum(channels_1.ChannelCategoryType);
exports.channelCategorySortingSchema = zod_1.z.enum(channels_1.ChannelCategorySorting);
exports.channelCategorySchema = zod_1.z.object({
    id: zod_1.z.string(),
    user_id: zod_1.z.string(),
    team_id: zod_1.z.string(),
    type: exports.channelCategoryTypeSchema,
    display_name: zod_1.z.string(),
    sorting: exports.channelCategorySortingSchema,
    channel_ids: zod_1.z.array(zod_1.z.string()),
    muted: zod_1.z.boolean(),
    collapsed: zod_1.z.boolean()
});
exports.orderedChannelCategoriesSchema = zod_1.z.object({
    categories: zod_1.z.array(exports.channelCategorySchema),
    order: zod_1.z.array(zod_1.z.string())
});
exports.channelBookmarkTypeSchema = zod_1.z.enum(channels_1.ChannelBookmarkType);
exports.channelBookmarkCreateLinkSchema = zod_1.z.object({
    type: zod_1.z.literal(channels_1.ChannelBookmarkType.LINK),
    link_url: zod_1.z.string()
});
exports.channelBookmarkCreateFileSchema = zod_1.z.object({
    type: zod_1.z.literal(channels_1.ChannelBookmarkType.FILE),
    file_id: zod_1.z.string()
});
exports.channelBookmarkCreateBaseSchema = zod_1.z.object({
    display_name: zod_1.z.string(),
    image_url: zod_1.z.string().optional(),
    emoji: zod_1.z.string().optional()
});
exports.channelBookmarkCreateSchema = exports.channelBookmarkCreateBaseSchema.and(zod_1.z.union([exports.channelBookmarkCreateLinkSchema, exports.channelBookmarkCreateFileSchema]));
exports.channelBookmarkPatchSchema = zod_1.z.object({
    file_id: zod_1.z.string().optional(),
    display_name: zod_1.z.string().optional(),
    sort_order: zod_1.z.number().optional(),
    link_url: zod_1.z.string().optional(),
    image_url: zod_1.z.string().optional(),
    emoji: zod_1.z.string().optional()
});
exports.channelMessageCountSchema = zod_1.z.object({
    total: zod_1.z.number(),
    root: zod_1.z.number()
});
exports.channelModerationSchema = zod_1.z.object({
    name: zod_1.z.string(),
    roles: zod_1.z.object({
        guests: zod_1.z
            .object({
            value: zod_1.z.boolean(),
            enabled: zod_1.z.boolean()
        })
            .optional(),
        members: zod_1.z.object({
            value: zod_1.z.boolean(),
            enabled: zod_1.z.boolean()
        }),
        admins: zod_1.z.object({
            value: zod_1.z.boolean(),
            enabled: zod_1.z.boolean()
        })
    })
});
exports.channelModerationPatchSchema = zod_1.z.object({
    name: zod_1.z.string(),
    roles: zod_1.z.object({
        guests: zod_1.z.boolean().optional(),
        members: zod_1.z.boolean().optional()
    })
});
exports.channelWithTeamDataSchema = exports.channelSchema.extend({
    team_display_name: zod_1.z.string(),
    team_name: zod_1.z.string(),
    team_update_at: zod_1.z.number()
});
exports.channelsWithTotalCountSchema = zod_1.z.object({
    channels: zod_1.z.array(exports.channelWithTeamDataSchema),
    total_count: zod_1.z.number()
});
exports.channelMemberCountByGroupSchema = zod_1.z.object({
    group_id: zod_1.z.string(),
    channel_member_count: zod_1.z.number(),
    channel_member_timezones_count: zod_1.z.number()
});
exports.channelMemberCountsByGroupSchema = zod_1.z.record(zod_1.z.string(), exports.channelMemberCountByGroupSchema);
exports.channelViewResponseSchema = zod_1.z.object({
    status: zod_1.z.string(),
    last_viewed_at_times: zod_1.z.record(zod_1.z.string(), zod_1.z.number())
});
exports.channelStatsSchema = zod_1.z.object({
    channel_id: zod_1.z.string(),
    member_count: zod_1.z.number(),
    guest_count: zod_1.z.number(),
    pinnedpost_count: zod_1.z.number(),
    files_count: zod_1.z.number()
});
exports.channelNotifyPropsResponseSchema = zod_1.z.object({
    desktop_threads: exports.channelNotifySchema,
    desktop: exports.channelNotifySchema,
    desktop_sound: zod_1.z.union([zod_1.z.literal("on"), zod_1.z.literal("off")]),
    desktop_notification_sound: exports.channelNotifyDesktopSoundSchema.optional(),
    email: exports.channelNotifySchema,
    mark_unread: exports.channelNotifySchema,
    push: exports.channelNotifySchema,
    push_threads: exports.channelNotifySchema,
    ignore_channel_mentions: zod_1.z.union([
        zod_1.z.literal("default"),
        zod_1.z.literal("off"),
        zod_1.z.literal("on")
    ]),
    channel_auto_follow_threads: zod_1.z.union([zod_1.z.literal("off"), zod_1.z.literal("on")])
});
exports.channelUnreadResponseSchema = zod_1.z.object({
    channel_id: zod_1.z.string(),
    user_id: zod_1.z.string(),
    team_id: zod_1.z.string(),
    msg_count: zod_1.z.number(),
    msg_count_root: zod_1.z.number(),
    mention_count: zod_1.z.number(),
    urgent_mention_count: zod_1.z.number(),
    mention_count_root: zod_1.z.number(),
    last_viewed_at: zod_1.z.number(),
    deltaMsgs: zod_1.z.number()
});
const fileInfoSchema = zod_1.z.any();
exports.serverChannelSchema = exports.channelSchema.extend({
    total_msg_count: zod_1.z.number(),
    total_msg_count_root: zod_1.z.number()
});
exports.channelBookmarkSchema = zod_1.z.object({
    id: zod_1.z.string(),
    create_at: zod_1.z.number(),
    update_at: zod_1.z.number(),
    delete_at: zod_1.z.number(),
    channel_id: zod_1.z.string(),
    owner_id: zod_1.z.string(),
    file_id: zod_1.z.string().optional(),
    file: fileInfoSchema.optional(),
    display_name: zod_1.z.string(),
    sort_order: zod_1.z.number(),
    link_url: zod_1.z.string().optional(),
    image_url: zod_1.z.string().optional(),
    emoji: zod_1.z.string().optional(),
    type: exports.channelBookmarkTypeSchema,
    original_id: zod_1.z.string().optional(),
    parent_id: zod_1.z.string().optional()
});
exports.channelBookmarkWithFileInfoSchema = exports.channelBookmarkSchema.extend({
    file: fileInfoSchema.optional()
});
exports.channelMembershipSchema = zod_1.z.object({
    channel_id: zod_1.z.string(),
    user_id: zod_1.z.string(),
    roles: zod_1.z.string(),
    last_viewed_at: zod_1.z.number(),
    msg_count: zod_1.z.number(),
    msg_count_root: zod_1.z.number(),
    mention_count: zod_1.z.number(),
    mention_count_root: zod_1.z.number(),
    urgent_mention_count: zod_1.z.number(),
    notify_props: exports.channelNotifyPropsResponseSchema.partial(),
    last_update_at: zod_1.z.number(),
    scheme_user: zod_1.z.boolean(),
    scheme_admin: zod_1.z.boolean(),
    post_root_id: zod_1.z.string().optional()
});
//# sourceMappingURL=channels.zod.js.map