// Generated by ts-to-zod
import { z } from "zod";
import { SelectDataSource } from "./common";

export const selectDataSourceSchema = z.enum(SelectDataSource);

export const optionSchema = z.object({
	value: z
		.string()
		.describe("Machine-facing value. Must be unique on this field."),
	label: z
		.string()
		.optional()
		.describe(
			"Label and text are user-facing strings\nThey default to value or to each other when undefined and must be unique."
		),
	text: z.string().optional(),
	icon_data: z
		.string()
		.optional()
		.describe(
			"Either a fully-qualified URL, or a path for an app's static asset\nUsed only in options for app form fields"
		)
});

export const dataSourceSchema = z.object({
	data_source: selectDataSourceSchema.optional()
});

export const optionsSchema = z.object({
	options: z.array(optionSchema).optional()
});

export const minMaxLentghSchema = z.object({
	min_length: z
		.number()
		.optional()
		.describe("Minimum input length allowed for an element.")
		.default(0),
	max_length: z
		.number()
		.optional()
		.describe(
			"Maximum input length allowed for an element.\n\nIf you expect the input to be greater 150 characters, consider using a textarea type element instead."
		)
		.default("150.")
});
