"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.statusOkResponseSchema = void 0;
// Generated by ts-to-zod
const zod_1 = require("zod");
exports.statusOkResponseSchema = zod_1.z.object({
    status: zod_1.z.literal("OK")
});
//# sourceMappingURL=common.responses.zod.js.map