"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.minMaxLentghSchema = exports.optionsSchema = exports.dataSourceSchema = exports.optionSchema = exports.selectDataSourceSchema = void 0;
// Generated by ts-to-zod
const zod_1 = require("zod");
const common_1 = require("./common");
exports.selectDataSourceSchema = zod_1.z.enum(common_1.SelectDataSource);
exports.optionSchema = zod_1.z.object({
    value: zod_1.z
        .string()
        .describe("Machine-facing value. Must be unique on this field."),
    label: zod_1.z
        .string()
        .optional()
        .describe("Label and text are user-facing strings\nThey default to value or to each other when undefined and must be unique."),
    text: zod_1.z.string().optional(),
    icon_data: zod_1.z
        .string()
        .optional()
        .describe("Either a fully-qualified URL, or a path for an app's static asset\nUsed only in options for app form fields")
});
exports.dataSourceSchema = zod_1.z.object({
    data_source: exports.selectDataSourceSchema.optional()
});
exports.optionsSchema = zod_1.z.object({
    options: zod_1.z.array(exports.optionSchema).optional()
});
exports.minMaxLentghSchema = zod_1.z.object({
    min_length: zod_1.z
        .number()
        .optional()
        .describe("Minimum input length allowed for an element.")
        .default(0),
    max_length: zod_1.z
        .number()
        .optional()
        .describe("Maximum input length allowed for an element.\n\nIf you expect the input to be greater 150 characters, consider using a textarea type element instead.")
        .default("150.")
});
//# sourceMappingURL=common.zod.js.map