"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.emojiSchema = exports.systemEmojiSchema = exports.systemEmojiVariationSchema = exports.recentEmojiDataSchema = exports.customEmojiSchema = exports.emojiCategorySchema = void 0;
// Generated by ts-to-zod
const zod_1 = require("zod");
const emojis_1 = require("./emojis");
exports.emojiCategorySchema = zod_1.z.enum(emojis_1.EmojiCategory);
exports.customEmojiSchema = zod_1.z.object({
    id: zod_1.z.string(),
    name: zod_1.z.string(),
    category: zod_1.z.literal(emojis_1.EmojiCategory.CUSTOM),
    create_at: zod_1.z.number(),
    update_at: zod_1.z.number(),
    delete_at: zod_1.z.number(),
    creator_id: zod_1.z.string()
});
exports.recentEmojiDataSchema = zod_1.z.object({
    name: zod_1.z.string(),
    usageCount: zod_1.z.number()
});
exports.systemEmojiVariationSchema = zod_1.z.object({
    unified: zod_1.z.string(),
    non_qualified: zod_1.z.null(),
    image: zod_1.z.string(),
    sheet_x: zod_1.z.number(),
    sheet_y: zod_1.z.number(),
    added_in: zod_1.z.string(),
    has_img_apple: zod_1.z.boolean(),
    has_img_google: zod_1.z.boolean(),
    has_img_twitter: zod_1.z.boolean(),
    has_img_facebook: zod_1.z.boolean()
});
exports.systemEmojiSchema = zod_1.z.object({
    name: zod_1.z.string(),
    category: exports.emojiCategorySchema,
    image: zod_1.z.string(),
    short_name: zod_1.z.string(),
    short_names: zod_1.z.array(zod_1.z.string()),
    batch: zod_1.z.number(),
    skins: zod_1.z.array(zod_1.z.string()).optional(),
    skin_variations: zod_1.z.record(zod_1.z.string(), exports.systemEmojiVariationSchema).optional(),
    unified: zod_1.z.string()
});
exports.emojiSchema = zod_1.z.union([exports.systemEmojiSchema, exports.customEmojiSchema]);
//# sourceMappingURL=emojis.zod.js.map