"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.fileSearchResultItemSchema = exports.fileInfoSchema = exports.uploadSessionSchema = void 0;
// Generated by ts-to-zod
const zod_1 = require("zod");
exports.uploadSessionSchema = zod_1.z.object({
    id: zod_1.z.string(),
    type: zod_1.z.string(),
    create_at: zod_1.z.number(),
    path: zod_1.z.string(),
    file_size: zod_1.z.number(),
    file_offset: zod_1.z.number()
});
exports.fileInfoSchema = zod_1.z.object({
    id: zod_1.z.string(),
    user_id: zod_1.z.string(),
    create_at: zod_1.z.number(),
    update_at: zod_1.z.number(),
    delete_at: zod_1.z.number(),
    name: zod_1.z.string(),
    extension: zod_1.z.string(),
    size: zod_1.z.number(),
    mime_type: zod_1.z.string(),
    width: zod_1.z.number(),
    height: zod_1.z.number(),
    has_preview_image: zod_1.z.boolean(),
    clientId: zod_1.z.string(),
    post_id: zod_1.z.string().optional(),
    mini_preview: zod_1.z.string().optional(),
    archived: zod_1.z.boolean(),
    link: zod_1.z.string().optional()
});
exports.fileSearchResultItemSchema = exports.fileInfoSchema.extend({
    channel_id: zod_1.z.string()
});
//# sourceMappingURL=files.zod.js.map