"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.draftSchema = exports.autocompleteUserSchema = exports.typingSchema = exports.termsOfServiceSchema = exports.searchParameterSchema = exports.searchSchema = exports.schemeSchema = exports.serverLimitsSchema = exports.samlMetadataResponseSchema = exports.samlCertificateStatusSchema = exports.reactionSchema = exports.productNoticeSchema = exports.preferenceSchema = exports.mfaSecretSchema = exports.dataRetentionCustomPoliciesSchema = exports.dataRetentionCustomPolicySchema = exports.complianceReportSchema = exports.completeOnboardingRequestSchema = exports.botSchema = exports.autocompleteSuggestionSchema = exports.auditSchema = void 0;
// Generated by ts-to-zod
const zod_1 = require("zod");
exports.auditSchema = zod_1.z.object({
    id: zod_1.z.string(),
    create_at: zod_1.z.number(),
    user_id: zod_1.z.string(),
    action: zod_1.z.string(),
    extra_info: zod_1.z.string(),
    ip_address: zod_1.z.string(),
    session_id: zod_1.z.string()
});
exports.autocompleteSuggestionSchema = zod_1.z.object({
    Complete: zod_1.z.string(),
    Suggestion: zod_1.z.string(),
    Hint: zod_1.z.string(),
    Description: zod_1.z.string(),
    IconData: zod_1.z.string()
});
exports.botSchema = zod_1.z.object({
    user_id: zod_1.z.string(),
    username: zod_1.z.string(),
    display_name: zod_1.z.string().optional(),
    description: zod_1.z.string().optional(),
    owner_id: zod_1.z.string(),
    create_at: zod_1.z.number(),
    update_at: zod_1.z.number(),
    delete_at: zod_1.z.number()
});
exports.completeOnboardingRequestSchema = zod_1.z.object({
    organization: zod_1.z.string(),
    install_plugins: zod_1.z.array(zod_1.z.string())
});
exports.complianceReportSchema = zod_1.z.object({
    id: zod_1.z.string(),
    create_at: zod_1.z.number(),
    user_id: zod_1.z.string(),
    status: zod_1.z.string(),
    count: zod_1.z.number(),
    desc: zod_1.z.string(),
    type: zod_1.z.string(),
    start_at: zod_1.z.number(),
    end_at: zod_1.z.number(),
    keywords: zod_1.z.string(),
    emails: zod_1.z.string()
});
exports.dataRetentionCustomPolicySchema = zod_1.z.object({
    id: zod_1.z.string(),
    display_name: zod_1.z.string(),
    post_duration: zod_1.z.number(),
    team_count: zod_1.z.number(),
    channel_count: zod_1.z.number()
});
exports.dataRetentionCustomPoliciesSchema = zod_1.z.record(zod_1.z.string(), exports.dataRetentionCustomPolicySchema);
exports.mfaSecretSchema = zod_1.z.object({
    secret: zod_1.z.string(),
    qr_code: zod_1.z.string()
});
exports.preferenceSchema = zod_1.z.object({
    user_id: zod_1.z.string(),
    category: zod_1.z.string(),
    name: zod_1.z.string(),
    value: zod_1.z.string()
});
exports.productNoticeSchema = zod_1.z.object({
    id: zod_1.z.string(),
    title: zod_1.z.string(),
    description: zod_1.z.string(),
    image: zod_1.z.string().optional(),
    actionText: zod_1.z.string().optional(),
    action: zod_1.z.union([zod_1.z.literal("url"), zod_1.z.literal("")]).optional(),
    actionParam: zod_1.z.string().optional(),
    sysAdminOnly: zod_1.z.boolean(),
    teamAdminOnly: zod_1.z.boolean()
});
exports.reactionSchema = zod_1.z.object({
    user_id: zod_1.z.string(),
    post_id: zod_1.z.string(),
    emoji_name: zod_1.z.string(),
    create_at: zod_1.z.number()
});
exports.samlCertificateStatusSchema = zod_1.z.object({
    idp_certificate_file: zod_1.z.string(),
    private_key_file: zod_1.z.string(),
    public_certificate_file: zod_1.z.string()
});
exports.samlMetadataResponseSchema = zod_1.z.object({
    idp_descriptor_url: zod_1.z.string(),
    idp_url: zod_1.z.string(),
    idp_public_certificate: zod_1.z.string()
});
exports.serverLimitsSchema = zod_1.z.object({
    activeUserCount: zod_1.z.number(),
    maxUsersLimit: zod_1.z.number()
});
exports.schemeSchema = zod_1.z.object({
    id: zod_1.z.string(),
    name: zod_1.z.string(),
    description: zod_1.z.string(),
    display_name: zod_1.z.string(),
    create_at: zod_1.z.number(),
    update_at: zod_1.z.number(),
    delete_at: zod_1.z.number(),
    scope: zod_1.z.union([zod_1.z.literal("team"), zod_1.z.literal("channel")]),
    default_team_admin_role: zod_1.z.string(),
    default_team_user_role: zod_1.z.string(),
    default_team_guest_role: zod_1.z.string(),
    default_channel_admin_role: zod_1.z.string(),
    default_channel_user_role: zod_1.z.string(),
    default_channel_guest_role: zod_1.z.string(),
    default_playbook_admin_role: zod_1.z.string(),
    default_playbook_member_role: zod_1.z.string(),
    default_run_member_role: zod_1.z.string()
});
exports.searchSchema = zod_1.z.object({
    terms: zod_1.z.string(),
    isOrSearch: zod_1.z.boolean()
});
exports.searchParameterSchema = zod_1.z.object({
    terms: zod_1.z.string(),
    is_or_search: zod_1.z.boolean(),
    time_zone_offset: zod_1.z.number().optional(),
    page: zod_1.z.number(),
    per_page: zod_1.z.number(),
    include_deleted_channels: zod_1.z.boolean()
});
exports.termsOfServiceSchema = zod_1.z.object({
    id: zod_1.z.string(),
    create_at: zod_1.z.number(),
    user_id: zod_1.z.string(),
    text: zod_1.z.string()
});
exports.typingSchema = zod_1.z.record(zod_1.z.string(), zod_1.z.record(zod_1.z.string(), zod_1.z.number()));
const userProfileSchema = zod_1.z.any();
const postMetadataSchema = zod_1.z.any();
const postPriorityMetadataSchema = zod_1.z.any();
exports.autocompleteUserSchema = zod_1.z.object({
    users: zod_1.z.array(userProfileSchema),
    out_of_channel: zod_1.z.array(userProfileSchema).optional()
});
exports.draftSchema = zod_1.z.object({
    create_at: zod_1.z.number(),
    update_at: zod_1.z.number(),
    delete_at: zod_1.z.number(),
    user_id: zod_1.z.string(),
    channel_id: zod_1.z.string(),
    root_id: zod_1.z.string(),
    message: zod_1.z.string(),
    props: zod_1.z.record(zod_1.z.string(), zod_1.z.unknown()),
    file_ids: zod_1.z.array(zod_1.z.string()).optional(),
    metadata: postMetadataSchema.optional(),
    priority: postPriorityMetadataSchema.optional()
});
//# sourceMappingURL=general.zod.js.map