"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.openGraphMetadataSchema = exports.openGraphMetadataImageSchema = void 0;
// Generated by ts-to-zod
const zod_1 = require("zod");
exports.openGraphMetadataImageSchema = zod_1.z.object({
    secure_url: zod_1.z.string().optional(),
    url: zod_1.z.string(),
    type: zod_1.z.string().optional(),
    height: zod_1.z.number().optional(),
    width: zod_1.z.number().optional()
});
exports.openGraphMetadataSchema = zod_1.z.object({
    type: zod_1.z.string().optional(),
    title: zod_1.z.string().optional(),
    description: zod_1.z.string().optional(),
    site_name: zod_1.z.string().optional(),
    url: zod_1.z.string().optional(),
    images: zod_1.z.array(exports.openGraphMetadataImageSchema)
});
//# sourceMappingURL=metadata.zod.js.map