"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.pluginReduxSchema = exports.pluginsGetResponseSchema = exports.pluginsResponseSchema = exports.pluginManifestSchema = exports.pluginSettingsSchemaSchema = exports.pluginSettingSchema = exports.clientPluginManifestSchema = exports.pluginStatusReduxSchema = exports.pluginStatusSchema = exports.pluginSettingOptionSchema = exports.pluginManifestWebappSchema = exports.pluginManifestServerSchema = void 0;
// Generated by ts-to-zod
const zod_1 = require("zod");
const messageDescriptorSchema = zod_1.z.object({
    id: zod_1.z.string(),
    defaultMessage: zod_1.z.string()
});
exports.pluginManifestServerSchema = zod_1.z.object({
    executables: zod_1.z
        .object({
        "linux-amd64": zod_1.z.string().optional(),
        "darwin-amd64": zod_1.z.string().optional(),
        "windows-amd64": zod_1.z.string().optional()
    })
        .optional(),
    executable: zod_1.z.string()
});
exports.pluginManifestWebappSchema = zod_1.z.object({
    bundle_path: zod_1.z.string()
});
exports.pluginSettingOptionSchema = zod_1.z.object({
    display_name: zod_1.z.string(),
    value: zod_1.z.string()
});
exports.pluginStatusSchema = zod_1.z.object({
    plugin_id: zod_1.z.string(),
    cluster_id: zod_1.z.string(),
    plugin_path: zod_1.z.string(),
    state: zod_1.z.number(),
    name: zod_1.z.string(),
    description: zod_1.z.string(),
    version: zod_1.z.string()
});
const pluginInstanceSchema = zod_1.z.object({
    cluster_id: zod_1.z.string(),
    version: zod_1.z.string(),
    state: zod_1.z.number()
});
exports.pluginStatusReduxSchema = zod_1.z.object({
    id: zod_1.z.string(),
    name: zod_1.z.string(),
    description: zod_1.z.string(),
    version: zod_1.z.string(),
    active: zod_1.z.boolean(),
    state: zod_1.z.number(),
    error: zod_1.z.string().optional(),
    instances: zod_1.z.array(pluginInstanceSchema)
});
exports.clientPluginManifestSchema = zod_1.z.object({
    id: zod_1.z.string(),
    min_server_version: zod_1.z.string().optional(),
    version: zod_1.z.string(),
    webapp: zod_1.z.object({
        bundle_path: zod_1.z.string()
    })
});
exports.pluginSettingSchema = zod_1.z.object({
    key: zod_1.z.string(),
    display_name: zod_1.z.string(),
    type: zod_1.z.string(),
    help_text: zod_1.z.union([zod_1.z.string(), messageDescriptorSchema]),
    regenerate_help_text: zod_1.z.string().optional(),
    placeholder: zod_1.z.string(),
    default: zod_1.z.unknown(),
    options: zod_1.z.array(exports.pluginSettingOptionSchema).optional(),
    hosting: zod_1.z.union([zod_1.z.literal("on-prem"), zod_1.z.literal("cloud")]).optional()
});
exports.pluginSettingsSchemaSchema = zod_1.z.object({
    header: zod_1.z.string(),
    footer: zod_1.z.string(),
    settings: zod_1.z.array(exports.pluginSettingSchema)
});
exports.pluginManifestSchema = zod_1.z.object({
    id: zod_1.z.string(),
    name: zod_1.z.string(),
    description: zod_1.z.string().optional(),
    homepage_url: zod_1.z.string().optional(),
    support_url: zod_1.z.string().optional(),
    release_notes_url: zod_1.z.string().optional(),
    icon_path: zod_1.z.string().optional(),
    version: zod_1.z.string(),
    min_server_version: zod_1.z.string().optional(),
    translate: zod_1.z.boolean().optional(),
    server: exports.pluginManifestServerSchema.optional(),
    backend: exports.pluginManifestServerSchema.optional(),
    webapp: exports.pluginManifestWebappSchema.optional(),
    settings_schema: exports.pluginSettingsSchemaSchema.optional(),
    props: zod_1.z
        .record(zod_1.z.string(), zod_1.z.unknown())
        .and(zod_1.z.object({
        enterprise: zod_1.z.boolean(),
        experimental: zod_1.z.boolean()
    }))
        .optional()
});
exports.pluginsResponseSchema = zod_1.z.object({
    active: zod_1.z.array(exports.pluginManifestSchema),
    inactive: zod_1.z.array(exports.pluginManifestSchema)
});
exports.pluginsGetResponseSchema = zod_1.z.object({
    active: zod_1.z.array(exports.pluginManifestSchema),
    inactive: zod_1.z.array(exports.pluginManifestSchema)
});
exports.pluginReduxSchema = exports.pluginManifestSchema.and(zod_1.z.object({
    active: zod_1.z.boolean()
}));
//# sourceMappingURL=plugins.zod.js.map