"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.postActionResponsePayloadSchema = exports.postPreviewMetadataSchema = exports.postEmbedSchema = exports.postMetadataSchema = exports.postSchema = exports.postPropsSchema = exports.postAttachmentSchema = exports.postActionSchema = exports.postActionSelectSchema = exports.postInfoSchema = exports.postActivityEntrySchema = exports.messageHistorySchema = exports.postOrderBlockSchema = exports.postAnalyticsSchema = exports.postActionPayloadSchema = exports.postActionButtonSchema = exports.postActionTypeSchema = exports.postActionStyleSchema = exports.postAttachmentFieldSchema = exports.postAttachmentColorSchema = exports.postAcknowledgementSchema = exports.postImageSchema = exports.postPriorityMetadataSchema = exports.postTypeSchema = exports.postEmbedTypeSchema = exports.postPrioritySchema = exports.postStateSchema = void 0;
// Generated by ts-to-zod
const zod_1 = require("zod");
const posts_1 = require("./posts");
exports.postStateSchema = zod_1.z.enum(posts_1.PostState);
exports.postPrioritySchema = zod_1.z.enum(posts_1.PostPriority);
exports.postEmbedTypeSchema = zod_1.z.enum(posts_1.PostEmbedType);
exports.postTypeSchema = zod_1.z.enum(posts_1.PostType);
exports.postPriorityMetadataSchema = zod_1.z.object({
    priority: exports.postPrioritySchema,
    requested_ack: zod_1.z.boolean().optional(),
    persistent_notifications: zod_1.z.boolean().optional()
});
exports.postImageSchema = zod_1.z.object({
    format: zod_1.z.string(),
    frameCount: zod_1.z.number(),
    height: zod_1.z.number(),
    width: zod_1.z.number()
});
exports.postAcknowledgementSchema = zod_1.z.object({
    post_id: zod_1.z.string(),
    user_id: zod_1.z.string(),
    acknowledged_at: zod_1.z.number()
});
exports.postAttachmentColorSchema = zod_1.z.enum(posts_1.PostAttachmentColor);
exports.postAttachmentFieldSchema = zod_1.z.object({
    title: zod_1.z
        .string()
        .describe("A title shown in the table above the value.\nAs of"),
    value: zod_1.z
        .string()
        .describe("The text value of the field.\nIt can be formatted using Markdown.\nSupports"),
    short: zod_1.z
        .boolean()
        .optional()
        .describe("Optionally set to true or false (boolean) to\nindicate whether the value is short enough to be displayed beside other values.")
});
exports.postActionStyleSchema = zod_1.z.enum(posts_1.PostActionStyle);
exports.postActionTypeSchema = zod_1.z.enum(posts_1.PostActionType);
const buttonStyleSchema = zod_1.z.object({
    style: exports.postActionStyleSchema
        .optional()
        .describe("Button color\n\nButton actions support a style parameter to change the color of the button.\nThe possible values for style are: good, warning, danger, default, primary, and success.\n\nIt's also possible to pass a theme variable or a hex color, but we discourage this approach because it won't be resilient against theme changes.")
});
const postActionBaseSchema = zod_1.z.object({
    type: exports.postActionTypeSchema.describe("Action type - button or select"),
    id: zod_1.z
        .string()
        .describe('A per post unique identifier.\nMust not contain "_" or "-"'),
    name: zod_1.z.string().describe("Give your action a descriptive name."),
    integration: zod_1.z
        .object({
        url: zod_1.z
            .string()
            .describe("The actions are backed by an integration that handles HTTP POST requests when users select the message button.\nThe URL parameter determines where this action is sent. The request contains an application/json JSON string.\nAs of"),
        context: zod_1.z
            .unknown()
            .optional()
            .describe("The requests sent to the specified URL contain the user ID, post ID, channel ID, team ID, and any context that was provided in the action definition. If the post was of type Message Menus, then context also contains the selected_option field with the user-selected option value. The post ID can be used to, for example, delete or edit the post after selecting a message button.")
    })
        .describe("Integration params")
});
exports.postActionButtonSchema = postActionBaseSchema(buttonStyleSchema.shape).extend({
    type: zod_1.z.literal(posts_1.PostActionType.BUTTON)
});
exports.postActionPayloadSchema = zod_1.z.object({
    post_id: zod_1.z.string(),
    channel_id: zod_1.z.string(),
    user_id: zod_1.z.string(),
    team_id: zod_1.z.string().optional(),
    context: zod_1.z.unknown()
});
exports.postAnalyticsSchema = zod_1.z.object({
    channel_id: zod_1.z.string(),
    post_id: zod_1.z.string(),
    user_actual_id: zod_1.z.string(),
    root_id: zod_1.z.string(),
    priority: exports.postPrioritySchema.optional(),
    requested_ack: zod_1.z.union([zod_1.z.boolean(), zod_1.z.undefined()]).optional(),
    persistent_notifications: zod_1.z.union([zod_1.z.boolean(), zod_1.z.undefined()]).optional()
});
exports.postOrderBlockSchema = zod_1.z.object({
    order: zod_1.z.array(zod_1.z.string()),
    recent: zod_1.z.boolean().optional(),
    oldest: zod_1.z.boolean().optional()
});
exports.messageHistorySchema = zod_1.z.object({
    messages: zod_1.z.array(zod_1.z.string()),
    index: zod_1.z.object({
        post: zod_1.z.number(),
        comment: zod_1.z.number()
    })
});
exports.postActivityEntrySchema = zod_1.z.object({
    postType: exports.postTypeSchema,
    actorId: zod_1.z.array(zod_1.z.string()),
    userIds: zod_1.z.array(zod_1.z.string()),
    usernames: zod_1.z.array(zod_1.z.string())
});
exports.postInfoSchema = zod_1.z.object({
    channel_id: zod_1.z.string(),
    channel_type: zod_1.z.string(),
    channel_display_name: zod_1.z.string(),
    has_joined_channel: zod_1.z.boolean(),
    team_id: zod_1.z.string(),
    team_type: zod_1.z.string(),
    team_display_name: zod_1.z.string(),
    has_joined_team: zod_1.z.boolean()
});
const openGraphMetadataSchema = zod_1.z.any();
const customEmojiSchema = zod_1.z.any();
const fileInfoSchema = zod_1.z.any();
const reactionSchema = zod_1.z.any();
const dataSourceSchema = zod_1.z.any();
const optionsSchema = zod_1.z.any();
exports.postActionSelectSchema = postActionBaseSchema(dataSourceSchema)
    .extend(optionsSchema)
    .extend({
    type: zod_1.z.literal(posts_1.PostActionType.SELECT)
});
exports.postActionSchema = zod_1.z.union([
    exports.postActionButtonSchema,
    exports.postActionSelectSchema
]);
exports.postAttachmentSchema = zod_1.z.object({
    fallback: zod_1.z
        .string()
        .optional()
        .describe("A required plain-text summary of the attachment.\nThis is used in notifications, and in clients that don't support formatted text (e.g. IRC)."),
    color: zod_1.z
        .union([exports.postAttachmentColorSchema, zod_1.z.string()])
        .optional()
        .describe("A hex color code that will be used as the left border color for the attachment.\nIf not specified, it will default to match the channel sidebar header background color."),
    pretext: zod_1.z
        .string()
        .optional()
        .describe("An optional line of text that will be shown above the attachment.\nSupports"),
    text: zod_1.z.string(),
    author_name: zod_1.z
        .string()
        .optional()
        .describe("An optional name used to identify the author.\nIt will be included in a small section at the top of the attachment."),
    author_link: zod_1.z
        .string()
        .optional()
        .describe("An optional URL used to hyperlink the author_name.\nIf no author_name is specified, this field does nothing."),
    author_icon: zod_1.z
        .string()
        .optional()
        .describe("An optional URL used to display a 16x16 pixel icon beside the author_name."),
    title: zod_1.z
        .string()
        .optional()
        .describe("An optional title displayed below the author information in the attachment."),
    title_link: zod_1.z
        .string()
        .optional()
        .describe("An optional URL used to hyperlink the title. If no title is specified, this field does nothing."),
    fields: zod_1.z
        .array(exports.postAttachmentFieldSchema)
        .optional()
        .nullable()
        .describe("Fields can be included as an optional array within attachments,\nand are used to display information in a table format inside the attachment."),
    actions: zod_1.z
        .array(exports.postActionSchema)
        .optional()
        .describe("Post action array (buttons/selects) used in interactive messages"),
    image_url: zod_1.z
        .string()
        .optional()
        .describe("An optional URL to an image file (GIF, JPEG, PNG, BMP, or SVG)\nthat is displayed inside a message attachment."),
    thumb_url: zod_1.z
        .string()
        .optional()
        .describe("An optional URL to an image file (GIF, JPEG, PNG, BMP, or SVG) that is displayed as\na 75x75 pixel thumbnail on the right side of an attachment.\n\nWe recommend using an image that is already 75x75 pixels, but larger images will be scaled down with the aspect ratio maintained."),
    footer: zod_1.z
        .string()
        .optional()
        .describe("An optional line of text that will be displayed at the bottom of the attachment.\nFooters with more than 300 characters will be truncated with an ellipsis (\u2026)."),
    footer_icon: zod_1.z
        .string()
        .optional()
        .describe("An optional URL to an image file (GIF, JPEG, PNG, BMP, or SVG) that\nis displayed as a 16x16 pixel thumbnail before the footer text."),
    ts: zod_1.z.number().optional().nullable()
});
exports.postPropsSchema = zod_1.z.object({
    app_bindings: zod_1.z.array(zod_1.z.any()).optional(),
    attachments: zod_1.z.array(exports.postAttachmentSchema).optional(),
    from_bot: zod_1.z.union([zod_1.z.literal("true"), zod_1.z.literal("false")]).optional(),
    metadata: zod_1.z.unknown().optional(),
    disable_group_highlight: zod_1.z.boolean().optional(),
    locationReplyMessage: zod_1.z.union([zod_1.z.literal("CENTER"), zod_1.z.string()]).optional(),
    replyMessage: zod_1.z.string().optional()
});
exports.postSchema = zod_1.z.lazy(() => zod_1.z.object({
    id: zod_1.z.string(),
    create_at: zod_1.z
        .number()
        .describe("The time in milliseconds a post was created"),
    update_at: zod_1.z
        .number()
        .describe("The time in milliseconds a post was last updated"),
    delete_at: zod_1.z.number(),
    edit_at: zod_1.z.number(),
    root_id: zod_1.z.string(),
    channel_id: zod_1.z.string(),
    user_id: zod_1.z.string(),
    original_id: zod_1.z.string(),
    pending_post_id: zod_1.z.string(),
    message: zod_1.z.string(),
    type: exports.postTypeSchema,
    metadata: exports.postMetadataSchema,
    props: exports.postPropsSchema,
    file_ids: zod_1.z.array(zod_1.z.string()).optional(),
    hashtag: zod_1.z.string().optional(),
    reply_count: zod_1.z.number(),
    last_reply_at: zod_1.z.number(),
    participants: zod_1.z.array(zod_1.z.union([zod_1.z.any(), zod_1.z.string()])).nullable(),
    state: exports.postStateSchema.optional().describe("???"),
    filenames: zod_1.z.array(zod_1.z.string()).optional(),
    is_pinned: zod_1.z.boolean().optional(),
    message_source: zod_1.z.string().optional(),
    is_following: zod_1.z.boolean().optional()
}));
exports.postMetadataSchema = zod_1.z.lazy(() => zod_1.z.object({
    embeds: zod_1.z.array(exports.postEmbedSchema).optional(),
    emojis: zod_1.z.array(customEmojiSchema).optional(),
    files: zod_1.z.array(fileInfoSchema).optional(),
    images: zod_1.z.record(zod_1.z.string(), exports.postImageSchema).optional(),
    reactions: zod_1.z.array(reactionSchema).optional(),
    priority: exports.postPriorityMetadataSchema.optional(),
    acknowledgements: zod_1.z.array(exports.postAcknowledgementSchema).optional()
}));
exports.postEmbedSchema = zod_1.z.lazy(() => zod_1.z.object({
    type: exports.postEmbedTypeSchema,
    url: zod_1.z.string(),
    data: zod_1.z
        .union([openGraphMetadataSchema, exports.postPreviewMetadataSchema])
        .optional()
}));
exports.postPreviewMetadataSchema = zod_1.z.lazy(() => zod_1.z.object({
    post_id: zod_1.z.string(),
    post: exports.postSchema.optional(),
    channel_display_name: zod_1.z.string(),
    team_name: zod_1.z.string(),
    channel_type: zod_1.z.string(),
    channel_id: zod_1.z.string()
}));
exports.postActionResponsePayloadSchema = zod_1.z.lazy(() => zod_1.z.object({
    update: exports.postSchema.optional(),
    ephemeral_text: zod_1.z.string().optional()
}));
//# sourceMappingURL=posts.zod.js.map