"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.postSearchResponseSchema = exports.paginatedPostListResponseSchema = exports.postListResponseSchema = exports.postResponseSchema = exports.postPropsResponseSchema = exports.postAttachmentResponseSchema = exports.postActionResponseSchema = exports.postNotificationResponseSchema = exports.postsUsageResponseSchema = void 0;
// Generated by ts-to-zod
const zod_1 = require("zod");
exports.postsUsageResponseSchema = zod_1.z.object({
    count: zod_1.z.number()
});
exports.postNotificationResponseSchema = zod_1.z.object({
    status: zod_1.z.union([
        zod_1.z.literal("error"),
        zod_1.z.literal("not_sent"),
        zod_1.z.literal("unsupported"),
        zod_1.z.literal("success")
    ]),
    reason: zod_1.z.string().optional(),
    data: zod_1.z.string().optional()
});
const postActionSchema = zod_1.z.any();
const postAttachmentSchema = zod_1.z.any();
const postAttachmentFieldSchema = zod_1.z.any();
const postPropsSchema = zod_1.z.any();
exports.postActionResponseSchema = postActionSchema.and(zod_1.z.object({
    integration: zod_1.z.never()
}));
exports.postAttachmentResponseSchema = zod_1.z.object({
    actions: zod_1.z.array(exports.postActionResponseSchema),
    fields: zod_1.z.array(postAttachmentFieldSchema).nullable()
});
exports.postPropsResponseSchema = zod_1.z.object({
    attachments: zod_1.z.array(postAttachmentSchema).optional()
});
exports.postResponseSchema = zod_1.z.object({
    props: postPropsSchema,
    ts: zod_1.z.number().nullable()
});
exports.postListResponseSchema = zod_1.z.object({
    order: zod_1.z.array(zod_1.z.string()),
    posts: zod_1.z.record(zod_1.z.string(), exports.postResponseSchema),
    next_post_id: zod_1.z.string(),
    prev_post_id: zod_1.z.string(),
    first_inaccessible_post_time: zod_1.z.number()
});
exports.paginatedPostListResponseSchema = exports.postListResponseSchema.extend({
    has_next: zod_1.z.boolean()
});
exports.postSearchResponseSchema = exports.postListResponseSchema.extend({
    matches: zod_1.z.record(zod_1.z.string(), zod_1.z.array(zod_1.z.string()))
});
//# sourceMappingURL=posts.responses.zod.js.map