"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.preferenceSchema = void 0;
// Generated by ts-to-zod
const zod_1 = require("zod");
exports.preferenceSchema = zod_1.z.object({
    user_id: zod_1.z.string(),
    category: zod_1.z.string(),
    name: zod_1.z.string(),
    value: zod_1.z.string()
});
//# sourceMappingURL=preferences.zod.js.map