"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.reactionSchema = void 0;
// Generated by ts-to-zod
const zod_1 = require("zod");
exports.reactionSchema = zod_1.z.object({
    user_id: zod_1.z.string(),
    post_id: zod_1.z.string(),
    emoji_name: zod_1.z.string(),
    create_at: zod_1.z.number()
});
//# sourceMappingURL=reactions.zod.js.map