"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.roleSchema = exports.rolePermissionSchema = void 0;
// Generated by ts-to-zod
const zod_1 = require("zod");
const roles_1 = require("./roles");
exports.rolePermissionSchema = zod_1.z.enum(roles_1.RolePermission);
exports.roleSchema = zod_1.z.object({
    id: zod_1.z.string(),
    name: zod_1.z.string(),
    display_name: zod_1.z.string(),
    description: zod_1.z.string(),
    create_at: zod_1.z.number(),
    update_at: zod_1.z.number(),
    delete_at: zod_1.z.number(),
    permissions: zod_1.z.array(zod_1.z.union([exports.rolePermissionSchema, zod_1.z.string()])),
    scheme_managed: zod_1.z.boolean(),
    built_in: zod_1.z.boolean()
});
//# sourceMappingURL=roles.zod.js.map