"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RolePermission = void 0;
var RolePermission;
(function (RolePermission) {
    RolePermission["EDIT_BOOKMARK_PUBLIC_CHANNEL"] = "edit_bookmark_public_channel";
    RolePermission["REMOVE_REACTION"] = "remove_reaction";
    RolePermission["DELETE_PUBLIC_CHANNEL"] = "delete_public_channel";
    RolePermission["CREATE_POST"] = "create_post";
    RolePermission["MANAGE_PRIVATE_CHANNEL_PROPERTIES"] = "manage_private_channel_properties";
    RolePermission["ORDER_BOOKMARK_PRIVATE_CHANNEL"] = "order_bookmark_private_channel";
    RolePermission["USE_CHANNEL_MENTIONS"] = "use_channel_mentions";
    RolePermission["DELETE_BOOKMARK_PUBLIC_CHANNEL"] = "delete_bookmark_public_channel";
    RolePermission["GET_PUBLIC_LINK"] = "get_public_link";
    RolePermission["EDIT_POST"] = "edit_post";
    RolePermission["MANAGE_PUBLIC_CHANNEL_PROPERITES"] = "manage_public_channel_properties";
    RolePermission["EDIT_BOOKMARK_PRIVATE_CHANNEL"] = "edit_bookmark_private_channel";
    RolePermission["UPLOAD_FILE"] = "upload_file";
    RolePermission["ADD_REACTION"] = "add_reaction";
    RolePermission["MANAGE_PUBLIC_CHANNEL_MEMBERS"] = "manage_public_channel_members";
    RolePermission["DELETE_BOOKMARK_PRIVATE_CHANNEL"] = "delete_bookmark_private_channel";
    RolePermission["ADD_BOOKMARK_PRIVATE_CHANNEL"] = "add_bookmark_private_channel";
    RolePermission["READ_PRIVATE_CHANNEL_GROUPS"] = "read_private_channel_groups";
    RolePermission["MANAGE_PRIVATE_CHANNEL_MEMBERS"] = "manage_private_channel_members";
    RolePermission["ORDER_BOOKMARK_PUBLIC_CHANNEL"] = "order_bookmark_public_channel";
    RolePermission["READ_CHANNEL_CONTENT"] = "read_channel_content";
    RolePermission["READ_PUBLIC_CHANNEL_GROUPS"] = "read_public_channel_groups";
    RolePermission["READ_CHANNEL"] = "read_channel";
    RolePermission["DELETE_POST"] = "delete_post";
    RolePermission["USE_GROUP_MENTIONS"] = "use_group_mentions";
    RolePermission["DELETE_PRIVATE_CHANNEL"] = "delete_private_channel";
})(RolePermission || (exports.RolePermission = RolePermission = {}));
//# sourceMappingURL=roles.js.map