"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.teamSearchOptsSchema = exports.teamInviteWithErrorSchema = exports.pagedTeamSearchOptsSchema = exports.notPagedTeamSearchOptsSchema = exports.teamStatsSchema = exports.teamsWithCountSchema = exports.getTeamMembersOptsSchema = exports.teamSchema = exports.teamMembershipSchema = exports.teamUnreadSchema = exports.teamsUsageResponseSchema = exports.teamTypeSchema = void 0;
// Generated by ts-to-zod
const zod_1 = require("zod");
const teams_1 = require("./teams");
exports.teamTypeSchema = zod_1.z.enum(teams_1.TeamType);
exports.teamsUsageResponseSchema = zod_1.z.object({
    active: zod_1.z.number(),
    cloud_archived: zod_1.z.number()
});
exports.teamUnreadSchema = zod_1.z.object({
    team_id: zod_1.z.string(),
    mention_count: zod_1.z.number(),
    mention_count_root: zod_1.z.number(),
    msg_count: zod_1.z.number(),
    msg_count_root: zod_1.z.number(),
    thread_count: zod_1.z.number().optional(),
    thread_mention_count: zod_1.z.number().optional(),
    thread_urgent_mention_count: zod_1.z.number().optional()
});
exports.teamMembershipSchema = exports.teamUnreadSchema.extend({
    user_id: zod_1.z.string(),
    roles: zod_1.z.string(),
    delete_at: zod_1.z.number(),
    scheme_admin: zod_1.z.boolean(),
    scheme_guest: zod_1.z.boolean(),
    scheme_user: zod_1.z.boolean()
});
exports.teamSchema = zod_1.z.object({
    id: zod_1.z.string(),
    create_at: zod_1.z.number(),
    update_at: zod_1.z.number(),
    delete_at: zod_1.z.number(),
    display_name: zod_1.z.string(),
    name: zod_1.z.string(),
    description: zod_1.z.string(),
    email: zod_1.z.string(),
    type: exports.teamTypeSchema,
    company_name: zod_1.z.string(),
    allowed_domains: zod_1.z.string(),
    invite_id: zod_1.z.string(),
    allow_open_invite: zod_1.z.boolean(),
    scheme_id: zod_1.z.string(),
    group_constrained: zod_1.z.boolean(),
    policy_id: zod_1.z.string().optional().nullable(),
    last_team_icon_update: zod_1.z.number().optional()
});
exports.getTeamMembersOptsSchema = zod_1.z.object({
    sort: zod_1.z.literal("Username").optional(),
    exclude_deleted_users: zod_1.z.boolean().optional()
});
exports.teamsWithCountSchema = zod_1.z.object({
    teams: zod_1.z.array(exports.teamSchema),
    total_count: zod_1.z.number()
});
exports.teamStatsSchema = zod_1.z.object({
    team_id: zod_1.z.string(),
    total_member_count: zod_1.z.number(),
    active_member_count: zod_1.z.number()
});
exports.notPagedTeamSearchOptsSchema = zod_1.z.object({
    allow_open_invite: zod_1.z.boolean().optional(),
    group_constrained: zod_1.z.boolean().optional()
});
exports.pagedTeamSearchOptsSchema = exports.notPagedTeamSearchOptsSchema.extend({
    page: zod_1.z.number(),
    per_page: zod_1.z.number()
});
exports.teamInviteWithErrorSchema = zod_1.z.object({
    email: zod_1.z.string(),
    error: zod_1.z.object({
        id: zod_1.z.string(),
        message: zod_1.z.string()
    })
});
exports.teamSearchOptsSchema = zod_1.z.union([
    exports.pagedTeamSearchOptsSchema,
    exports.notPagedTeamSearchOptsSchema
]);
//# sourceMappingURL=teams.zod.js.map