"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.userSessionSchema = exports.userProfileWithLastViewedAtSchema = exports.authChangeResponseSchema = exports.getFilteredUsersStatsOptsSchema = exports.usersStatsSchema = exports.userAccessTokenSchema = exports.userCustomStatusSchema = exports.userStatusSchema = exports.userProfileSchema = exports.notifyPropsSchema = exports.customStatusDurationSchema = exports.userStatusValueSchema = exports.userCallSoundSchema = exports.userNotifySchema = exports.userTimezoneSchema = void 0;
// Generated by ts-to-zod
const zod_1 = require("zod");
const users_1 = require("./users");
exports.userTimezoneSchema = zod_1.z.object({
    useAutomaticTimezone: zod_1.z.union([
        zod_1.z.boolean(),
        zod_1.z.literal("true"),
        zod_1.z.literal("false")
    ]),
    automaticTimezone: zod_1.z.string(),
    manualTimezone: zod_1.z.string()
});
exports.userNotifySchema = zod_1.z.enum(users_1.UserNotify);
exports.userCallSoundSchema = zod_1.z.enum(users_1.UserCallSound);
exports.userStatusValueSchema = zod_1.z.enum(users_1.UserStatusValue);
exports.customStatusDurationSchema = zod_1.z.enum(users_1.CustomStatusDuration);
exports.notifyPropsSchema = zod_1.z.object({
    channel: zod_1.z.union([zod_1.z.literal("true"), zod_1.z.literal("false")]),
    comments: zod_1.z.union([zod_1.z.literal("never"), zod_1.z.literal("root"), zod_1.z.literal("any")]),
    desktop: exports.userNotifySchema,
    desktop_sound: zod_1.z.union([zod_1.z.literal("true"), zod_1.z.literal("false")]),
    desktop_threads: exports.userNotifySchema.optional(),
    desktop_notification_sound: zod_1.z
        .union([
        zod_1.z.literal("Bing"),
        zod_1.z.literal("Crackle"),
        zod_1.z.literal("Down"),
        zod_1.z.literal("Hello"),
        zod_1.z.literal("Ripple"),
        zod_1.z.literal("Upstairs")
    ])
        .optional(),
    email: zod_1.z.union([zod_1.z.literal("true"), zod_1.z.literal("false")]),
    email_threads: exports.userNotifySchema.optional(),
    first_name: zod_1.z.union([zod_1.z.literal("true"), zod_1.z.literal("false")]),
    loop_mobile_push_reactions: exports.userNotifySchema.optional(),
    loop_mobile_push_reactions_sound: zod_1.z
        .union([zod_1.z.literal("true"), zod_1.z.literal("false")])
        .optional(),
    loop_push_reactions: exports.userNotifySchema.optional(),
    loop_push_reactions_sound: zod_1.z
        .union([zod_1.z.literal("true"), zod_1.z.literal("false")])
        .optional(),
    mention_keys: zod_1.z.string(),
    push: exports.userNotifySchema,
    push_status: zod_1.z.union([
        zod_1.z.literal("ooo"),
        zod_1.z.literal("offline"),
        zod_1.z.literal("away"),
        zod_1.z.literal("dnd"),
        zod_1.z.literal("online")
    ]),
    push_threads: exports.userNotifySchema.optional(),
    auto_responder_active: zod_1.z
        .union([zod_1.z.literal("true"), zod_1.z.literal("false")])
        .optional(),
    auto_responder_message: zod_1.z.string().optional(),
    calls_notification_sound: exports.userCallSoundSchema.optional(),
    calls_desktop_sound: zod_1.z
        .union([zod_1.z.literal("true"), zod_1.z.literal("false")])
        .optional(),
    calls_mobile_sound: zod_1.z
        .union([zod_1.z.literal("true"), zod_1.z.literal("false"), zod_1.z.literal("")])
        .optional(),
    calls_mobile_notification_sound: exports.userCallSoundSchema.optional()
});
exports.userProfileSchema = zod_1.z.object({
    id: zod_1.z.string(),
    username: zod_1.z.union([zod_1.z.string(), zod_1.z.literal("")]).default(""),
    auth_data: zod_1.z.union([zod_1.z.string(), zod_1.z.literal("")]).default(""),
    auth_service: zod_1.z.union([zod_1.z.string(), zod_1.z.literal("")]).default(""),
    email: zod_1.z.string(),
    email_verified: zod_1.z.boolean().optional(),
    nickname: zod_1.z.string().default(""),
    first_name: zod_1.z.string().default(""),
    last_name: zod_1.z.string().default(""),
    position: zod_1.z.string().default(""),
    password: zod_1.z.string().optional().describe("excluded from responses"),
    create_at: zod_1.z.number().describe("Creation date unix timestamp"),
    update_at: zod_1.z.number().describe("Update date unix timestamp"),
    delete_at: zod_1.z
        .union([zod_1.z.number(), zod_1.z.literal(0)])
        .optional()
        .describe("Deletion date unix timestamp\nWill be zero if user is active")
        .default(0),
    roles: zod_1.z.string().describe("User roles in string format"),
    props: zod_1.z
        .record(zod_1.z.string(), zod_1.z.unknown())
        .and(zod_1.z.object({
        customStatus: zod_1.z
            .string()
            .optional()
            .describe("User custom status in stringified format")
    }))
        .optional()
        .describe("User profile props"),
    notify_props: exports.notifyPropsSchema.describe("Notification settings"),
    last_password_update: zod_1.z
        .number()
        .optional()
        .describe("Last password update timestamp"),
    last_picture_update: zod_1.z
        .number()
        .optional()
        .describe("Will be undefined if no picture was set"),
    locale: zod_1.z.string().default("'en'"),
    timezone: exports.userTimezoneSchema.optional(),
    remote_id: zod_1.z
        .union([zod_1.z.string(), zod_1.z.literal("")])
        .optional()
        .default(""),
    disable_welcome_email: zod_1.z.boolean().optional(),
    status: zod_1.z.string().optional(),
    mfa_active: zod_1.z.boolean().optional(),
    last_activity_at: zod_1.z.number().optional(),
    is_bot: zod_1.z.boolean().optional(),
    bot_description: zod_1.z.string().optional(),
    terms_of_service_id: zod_1.z.string().optional(),
    terms_of_service_create_at: zod_1.z.number().optional()
});
exports.userStatusSchema = zod_1.z.object({
    user_id: zod_1.z.string(),
    status: exports.userStatusValueSchema,
    manual: zod_1.z.boolean().optional(),
    last_activity_at: zod_1.z.number().optional(),
    active_channel: zod_1.z.string().optional(),
    dnd_end_time: zod_1.z.number().optional()
});
exports.userCustomStatusSchema = zod_1.z.object({
    emoji: zod_1.z.string(),
    text: zod_1.z.string(),
    duration: exports.customStatusDurationSchema,
    expires_at: zod_1.z.string().optional()
});
exports.userAccessTokenSchema = zod_1.z.object({
    id: zod_1.z.string(),
    token: zod_1.z.string().optional(),
    user_id: zod_1.z.string(),
    description: zod_1.z.string(),
    is_active: zod_1.z.boolean()
});
exports.usersStatsSchema = zod_1.z.object({
    total_users_count: zod_1.z.number()
});
exports.getFilteredUsersStatsOptsSchema = zod_1.z.object({
    in_team: zod_1.z.string().optional(),
    in_channel: zod_1.z.string().optional(),
    include_deleted: zod_1.z.boolean().optional(),
    include_bots: zod_1.z.boolean().optional(),
    include_remote_users: zod_1.z.boolean().optional(),
    roles: zod_1.z.array(zod_1.z.string()).optional(),
    channel_roles: zod_1.z.array(zod_1.z.string()).optional(),
    team_roles: zod_1.z.array(zod_1.z.string()).optional()
});
exports.authChangeResponseSchema = zod_1.z.object({
    follow_link: zod_1.z.string()
});
const teamMembershipSchema = zod_1.z.any();
exports.userProfileWithLastViewedAtSchema = exports.userProfileSchema.extend({
    last_viewed_at: zod_1.z.number()
});
exports.userSessionSchema = zod_1.z.object({
    id: zod_1.z.string(),
    token: zod_1.z.string(),
    create_at: zod_1.z.number(),
    expires_at: zod_1.z.number(),
    last_activity_at: zod_1.z.number(),
    user_id: zod_1.z.string(),
    device_id: zod_1.z.string(),
    roles: zod_1.z.string(),
    is_oauth: zod_1.z.boolean(),
    props: zod_1.z.record(zod_1.z.string(), zod_1.z.unknown()),
    team_members: zod_1.z.array(teamMembershipSchema),
    local: zod_1.z.boolean()
});
//# sourceMappingURL=users.zod.js.map