import { z } from "zod";
import { CustomStatusDuration, UserCallSound, UserNotify, UserStatusValue } from "./users";
export declare const userTimezoneSchema: z.ZodObject<{
    useAutomaticTimezone: z.ZodUnion<readonly [z.ZodBoolean, z.ZodLiteral<"true">, z.ZodLiteral<"false">]>;
    automaticTimezone: z.ZodString;
    manualTimezone: z.ZodString;
}, z.core.$strip>;
export declare const userNotifySchema: z.ZodEnum<typeof UserNotify>;
export declare const userCallSoundSchema: z.ZodEnum<typeof UserCallSound>;
export declare const userStatusValueSchema: z.ZodEnum<typeof UserStatusValue>;
export declare const customStatusDurationSchema: z.ZodEnum<typeof CustomStatusDuration>;
export declare const notifyPropsSchema: z.ZodObject<{
    channel: z.ZodUnion<readonly [z.ZodLiteral<"true">, z.ZodLiteral<"false">]>;
    comments: z.ZodUnion<readonly [z.ZodLiteral<"never">, z.ZodLiteral<"root">, z.ZodLiteral<"any">]>;
    desktop: z.ZodEnum<typeof UserNotify>;
    desktop_sound: z.ZodUnion<readonly [z.ZodLiteral<"true">, z.ZodLiteral<"false">]>;
    desktop_threads: z.ZodOptional<z.ZodEnum<typeof UserNotify>>;
    desktop_notification_sound: z.ZodOptional<z.ZodUnion<readonly [z.ZodLiteral<"Bing">, z.ZodLiteral<"Crackle">, z.ZodLiteral<"Down">, z.ZodLiteral<"Hello">, z.ZodLiteral<"Ripple">, z.ZodLiteral<"Upstairs">]>>;
    email: z.ZodUnion<readonly [z.ZodLiteral<"true">, z.ZodLiteral<"false">]>;
    email_threads: z.ZodOptional<z.ZodEnum<typeof UserNotify>>;
    first_name: z.ZodUnion<readonly [z.ZodLiteral<"true">, z.ZodLiteral<"false">]>;
    loop_mobile_push_reactions: z.ZodOptional<z.ZodEnum<typeof UserNotify>>;
    loop_mobile_push_reactions_sound: z.ZodOptional<z.ZodUnion<readonly [z.ZodLiteral<"true">, z.ZodLiteral<"false">]>>;
    loop_push_reactions: z.ZodOptional<z.ZodEnum<typeof UserNotify>>;
    loop_push_reactions_sound: z.ZodOptional<z.ZodUnion<readonly [z.ZodLiteral<"true">, z.ZodLiteral<"false">]>>;
    mention_keys: z.ZodString;
    push: z.ZodEnum<typeof UserNotify>;
    push_status: z.ZodUnion<readonly [z.ZodLiteral<"ooo">, z.ZodLiteral<"offline">, z.ZodLiteral<"away">, z.ZodLiteral<"dnd">, z.ZodLiteral<"online">]>;
    push_threads: z.ZodOptional<z.ZodEnum<typeof UserNotify>>;
    auto_responder_active: z.ZodOptional<z.ZodUnion<readonly [z.ZodLiteral<"true">, z.ZodLiteral<"false">]>>;
    auto_responder_message: z.ZodOptional<z.ZodString>;
    calls_notification_sound: z.ZodOptional<z.ZodEnum<typeof UserCallSound>>;
    calls_desktop_sound: z.ZodOptional<z.ZodUnion<readonly [z.ZodLiteral<"true">, z.ZodLiteral<"false">]>>;
    calls_mobile_sound: z.ZodOptional<z.ZodUnion<readonly [z.ZodLiteral<"true">, z.ZodLiteral<"false">, z.ZodLiteral<"">]>>;
    calls_mobile_notification_sound: z.ZodOptional<z.ZodEnum<typeof UserCallSound>>;
}, z.core.$strip>;
export declare const userProfileSchema: z.ZodObject<{
    id: z.ZodString;
    username: z.ZodDefault<z.ZodUnion<readonly [z.ZodString, z.ZodLiteral<"">]>>;
    auth_data: z.ZodDefault<z.ZodUnion<readonly [z.ZodString, z.ZodLiteral<"">]>>;
    auth_service: z.ZodDefault<z.ZodUnion<readonly [z.ZodString, z.ZodLiteral<"">]>>;
    email: z.ZodString;
    email_verified: z.ZodOptional<z.ZodBoolean>;
    nickname: z.ZodDefault<z.ZodString>;
    first_name: z.ZodDefault<z.ZodString>;
    last_name: z.ZodDefault<z.ZodString>;
    position: z.ZodDefault<z.ZodString>;
    password: z.ZodOptional<z.ZodString>;
    create_at: z.ZodNumber;
    update_at: z.ZodNumber;
    delete_at: z.ZodDefault<z.ZodOptional<z.ZodUnion<readonly [z.ZodNumber, z.ZodLiteral<0>]>>>;
    roles: z.ZodString;
    props: z.ZodOptional<z.ZodIntersection<z.ZodRecord<z.ZodString, z.ZodUnknown>, z.ZodObject<{
        customStatus: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>>;
    notify_props: z.ZodObject<{
        channel: z.ZodUnion<readonly [z.ZodLiteral<"true">, z.ZodLiteral<"false">]>;
        comments: z.ZodUnion<readonly [z.ZodLiteral<"never">, z.ZodLiteral<"root">, z.ZodLiteral<"any">]>;
        desktop: z.ZodEnum<typeof UserNotify>;
        desktop_sound: z.ZodUnion<readonly [z.ZodLiteral<"true">, z.ZodLiteral<"false">]>;
        desktop_threads: z.ZodOptional<z.ZodEnum<typeof UserNotify>>;
        desktop_notification_sound: z.ZodOptional<z.ZodUnion<readonly [z.ZodLiteral<"Bing">, z.ZodLiteral<"Crackle">, z.ZodLiteral<"Down">, z.ZodLiteral<"Hello">, z.ZodLiteral<"Ripple">, z.ZodLiteral<"Upstairs">]>>;
        email: z.ZodUnion<readonly [z.ZodLiteral<"true">, z.ZodLiteral<"false">]>;
        email_threads: z.ZodOptional<z.ZodEnum<typeof UserNotify>>;
        first_name: z.ZodUnion<readonly [z.ZodLiteral<"true">, z.ZodLiteral<"false">]>;
        loop_mobile_push_reactions: z.ZodOptional<z.ZodEnum<typeof UserNotify>>;
        loop_mobile_push_reactions_sound: z.ZodOptional<z.ZodUnion<readonly [z.ZodLiteral<"true">, z.ZodLiteral<"false">]>>;
        loop_push_reactions: z.ZodOptional<z.ZodEnum<typeof UserNotify>>;
        loop_push_reactions_sound: z.ZodOptional<z.ZodUnion<readonly [z.ZodLiteral<"true">, z.ZodLiteral<"false">]>>;
        mention_keys: z.ZodString;
        push: z.ZodEnum<typeof UserNotify>;
        push_status: z.ZodUnion<readonly [z.ZodLiteral<"ooo">, z.ZodLiteral<"offline">, z.ZodLiteral<"away">, z.ZodLiteral<"dnd">, z.ZodLiteral<"online">]>;
        push_threads: z.ZodOptional<z.ZodEnum<typeof UserNotify>>;
        auto_responder_active: z.ZodOptional<z.ZodUnion<readonly [z.ZodLiteral<"true">, z.ZodLiteral<"false">]>>;
        auto_responder_message: z.ZodOptional<z.ZodString>;
        calls_notification_sound: z.ZodOptional<z.ZodEnum<typeof UserCallSound>>;
        calls_desktop_sound: z.ZodOptional<z.ZodUnion<readonly [z.ZodLiteral<"true">, z.ZodLiteral<"false">]>>;
        calls_mobile_sound: z.ZodOptional<z.ZodUnion<readonly [z.ZodLiteral<"true">, z.ZodLiteral<"false">, z.ZodLiteral<"">]>>;
        calls_mobile_notification_sound: z.ZodOptional<z.ZodEnum<typeof UserCallSound>>;
    }, z.core.$strip>;
    last_password_update: z.ZodOptional<z.ZodNumber>;
    last_picture_update: z.ZodOptional<z.ZodNumber>;
    locale: z.ZodDefault<z.ZodString>;
    timezone: z.ZodOptional<z.ZodObject<{
        useAutomaticTimezone: z.ZodUnion<readonly [z.ZodBoolean, z.ZodLiteral<"true">, z.ZodLiteral<"false">]>;
        automaticTimezone: z.ZodString;
        manualTimezone: z.ZodString;
    }, z.core.$strip>>;
    remote_id: z.ZodDefault<z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodLiteral<"">]>>>;
    disable_welcome_email: z.ZodOptional<z.ZodBoolean>;
    status: z.ZodOptional<z.ZodString>;
    mfa_active: z.ZodOptional<z.ZodBoolean>;
    last_activity_at: z.ZodOptional<z.ZodNumber>;
    is_bot: z.ZodOptional<z.ZodBoolean>;
    bot_description: z.ZodOptional<z.ZodString>;
    terms_of_service_id: z.ZodOptional<z.ZodString>;
    terms_of_service_create_at: z.ZodOptional<z.ZodNumber>;
}, z.core.$strip>;
export declare const userStatusSchema: z.ZodObject<{
    user_id: z.ZodString;
    status: z.ZodEnum<typeof UserStatusValue>;
    manual: z.ZodOptional<z.ZodBoolean>;
    last_activity_at: z.ZodOptional<z.ZodNumber>;
    active_channel: z.ZodOptional<z.ZodString>;
    dnd_end_time: z.ZodOptional<z.ZodNumber>;
}, z.core.$strip>;
export declare const userCustomStatusSchema: z.ZodObject<{
    emoji: z.ZodString;
    text: z.ZodString;
    duration: z.ZodEnum<typeof CustomStatusDuration>;
    expires_at: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const userAccessTokenSchema: z.ZodObject<{
    id: z.ZodString;
    token: z.ZodOptional<z.ZodString>;
    user_id: z.ZodString;
    description: z.ZodString;
    is_active: z.ZodBoolean;
}, z.core.$strip>;
export declare const usersStatsSchema: z.ZodObject<{
    total_users_count: z.ZodNumber;
}, z.core.$strip>;
export declare const getFilteredUsersStatsOptsSchema: z.ZodObject<{
    in_team: z.ZodOptional<z.ZodString>;
    in_channel: z.ZodOptional<z.ZodString>;
    include_deleted: z.ZodOptional<z.ZodBoolean>;
    include_bots: z.ZodOptional<z.ZodBoolean>;
    include_remote_users: z.ZodOptional<z.ZodBoolean>;
    roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
    channel_roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
    team_roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
}, z.core.$strip>;
export declare const authChangeResponseSchema: z.ZodObject<{
    follow_link: z.ZodString;
}, z.core.$strip>;
export declare const userProfileWithLastViewedAtSchema: z.ZodObject<{
    id: z.ZodString;
    username: z.ZodDefault<z.ZodUnion<readonly [z.ZodString, z.ZodLiteral<"">]>>;
    auth_data: z.ZodDefault<z.ZodUnion<readonly [z.ZodString, z.ZodLiteral<"">]>>;
    auth_service: z.ZodDefault<z.ZodUnion<readonly [z.ZodString, z.ZodLiteral<"">]>>;
    email: z.ZodString;
    email_verified: z.ZodOptional<z.ZodBoolean>;
    nickname: z.ZodDefault<z.ZodString>;
    first_name: z.ZodDefault<z.ZodString>;
    last_name: z.ZodDefault<z.ZodString>;
    position: z.ZodDefault<z.ZodString>;
    password: z.ZodOptional<z.ZodString>;
    create_at: z.ZodNumber;
    update_at: z.ZodNumber;
    delete_at: z.ZodDefault<z.ZodOptional<z.ZodUnion<readonly [z.ZodNumber, z.ZodLiteral<0>]>>>;
    roles: z.ZodString;
    props: z.ZodOptional<z.ZodIntersection<z.ZodRecord<z.ZodString, z.ZodUnknown>, z.ZodObject<{
        customStatus: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>>;
    notify_props: z.ZodObject<{
        channel: z.ZodUnion<readonly [z.ZodLiteral<"true">, z.ZodLiteral<"false">]>;
        comments: z.ZodUnion<readonly [z.ZodLiteral<"never">, z.ZodLiteral<"root">, z.ZodLiteral<"any">]>;
        desktop: z.ZodEnum<typeof UserNotify>;
        desktop_sound: z.ZodUnion<readonly [z.ZodLiteral<"true">, z.ZodLiteral<"false">]>;
        desktop_threads: z.ZodOptional<z.ZodEnum<typeof UserNotify>>;
        desktop_notification_sound: z.ZodOptional<z.ZodUnion<readonly [z.ZodLiteral<"Bing">, z.ZodLiteral<"Crackle">, z.ZodLiteral<"Down">, z.ZodLiteral<"Hello">, z.ZodLiteral<"Ripple">, z.ZodLiteral<"Upstairs">]>>;
        email: z.ZodUnion<readonly [z.ZodLiteral<"true">, z.ZodLiteral<"false">]>;
        email_threads: z.ZodOptional<z.ZodEnum<typeof UserNotify>>;
        first_name: z.ZodUnion<readonly [z.ZodLiteral<"true">, z.ZodLiteral<"false">]>;
        loop_mobile_push_reactions: z.ZodOptional<z.ZodEnum<typeof UserNotify>>;
        loop_mobile_push_reactions_sound: z.ZodOptional<z.ZodUnion<readonly [z.ZodLiteral<"true">, z.ZodLiteral<"false">]>>;
        loop_push_reactions: z.ZodOptional<z.ZodEnum<typeof UserNotify>>;
        loop_push_reactions_sound: z.ZodOptional<z.ZodUnion<readonly [z.ZodLiteral<"true">, z.ZodLiteral<"false">]>>;
        mention_keys: z.ZodString;
        push: z.ZodEnum<typeof UserNotify>;
        push_status: z.ZodUnion<readonly [z.ZodLiteral<"ooo">, z.ZodLiteral<"offline">, z.ZodLiteral<"away">, z.ZodLiteral<"dnd">, z.ZodLiteral<"online">]>;
        push_threads: z.ZodOptional<z.ZodEnum<typeof UserNotify>>;
        auto_responder_active: z.ZodOptional<z.ZodUnion<readonly [z.ZodLiteral<"true">, z.ZodLiteral<"false">]>>;
        auto_responder_message: z.ZodOptional<z.ZodString>;
        calls_notification_sound: z.ZodOptional<z.ZodEnum<typeof UserCallSound>>;
        calls_desktop_sound: z.ZodOptional<z.ZodUnion<readonly [z.ZodLiteral<"true">, z.ZodLiteral<"false">]>>;
        calls_mobile_sound: z.ZodOptional<z.ZodUnion<readonly [z.ZodLiteral<"true">, z.ZodLiteral<"false">, z.ZodLiteral<"">]>>;
        calls_mobile_notification_sound: z.ZodOptional<z.ZodEnum<typeof UserCallSound>>;
    }, z.core.$strip>;
    last_password_update: z.ZodOptional<z.ZodNumber>;
    last_picture_update: z.ZodOptional<z.ZodNumber>;
    locale: z.ZodDefault<z.ZodString>;
    timezone: z.ZodOptional<z.ZodObject<{
        useAutomaticTimezone: z.ZodUnion<readonly [z.ZodBoolean, z.ZodLiteral<"true">, z.ZodLiteral<"false">]>;
        automaticTimezone: z.ZodString;
        manualTimezone: z.ZodString;
    }, z.core.$strip>>;
    remote_id: z.ZodDefault<z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodLiteral<"">]>>>;
    disable_welcome_email: z.ZodOptional<z.ZodBoolean>;
    status: z.ZodOptional<z.ZodString>;
    mfa_active: z.ZodOptional<z.ZodBoolean>;
    last_activity_at: z.ZodOptional<z.ZodNumber>;
    is_bot: z.ZodOptional<z.ZodBoolean>;
    bot_description: z.ZodOptional<z.ZodString>;
    terms_of_service_id: z.ZodOptional<z.ZodString>;
    terms_of_service_create_at: z.ZodOptional<z.ZodNumber>;
    last_viewed_at: z.ZodNumber;
}, z.core.$strip>;
export declare const userSessionSchema: z.ZodObject<{
    id: z.ZodString;
    token: z.ZodString;
    create_at: z.ZodNumber;
    expires_at: z.ZodNumber;
    last_activity_at: z.ZodNumber;
    user_id: z.ZodString;
    device_id: z.ZodString;
    roles: z.ZodString;
    is_oauth: z.ZodBoolean;
    props: z.ZodRecord<z.ZodString, z.ZodUnknown>;
    team_members: z.ZodArray<z.ZodAny>;
    local: z.ZodBoolean;
}, z.core.$strip>;
//# sourceMappingURL=users.zod.d.ts.map