// Generated by ts-to-zod
import { z } from "zod";
import {
	type AppBinding,
	AppExpandLevel,
	AppFormFieldTextSubType,
	AppFormFieldType,
	AppLocation,
	AppPermission,
	AppRequestedLocation
} from "./apps";

export const appPermissionSchema = z.enum(AppPermission);

export const appRequestedLocationSchema = z.enum(AppRequestedLocation);

export const appManifestSchema = z.object({
	app_id: z.string(),
	version: z.string().optional(),
	homepage_url: z.string().optional(),
	icon: z.string().optional(),
	display_name: z.string(),
	description: z.string().optional(),
	requested_permissions: z.array(appPermissionSchema).optional(),
	requested_locations: z.array(appRequestedLocationSchema).optional()
});

export const appExpandLevelSchema = z.enum(AppExpandLevel);

export const appExpandSchema = z.object({
	app: appExpandLevelSchema.optional(),
	acting_user: appExpandLevelSchema.optional(),
	acting_user_access_token: appExpandLevelSchema.optional(),
	channel: appExpandLevelSchema.optional(),
	config: appExpandLevelSchema.optional(),
	mentioned: appExpandLevelSchema.optional(),
	parent_post: appExpandLevelSchema.optional(),
	post: appExpandLevelSchema.optional(),
	root_post: appExpandLevelSchema.optional(),
	team: appExpandLevelSchema.optional(),
	user: appExpandLevelSchema.optional(),
	locale: appExpandLevelSchema.optional()
});

export const appContextSchema = z.object({
	app_id: z.string(),
	location: z.string().optional(),
	acting_user_id: z.string().optional(),
	user_id: z.string().optional(),
	channel_id: z.string().optional(),
	team_id: z.string().optional(),
	post_id: z.string().optional(),
	root_id: z.string().optional(),
	props: z.any().optional(),
	user_agent: z.string().optional(),
	track_as_submit: z.boolean().optional()
});

export const appCallMetadataForClientSchema = z.object({
	bot_user_id: z.string(),
	bot_username: z.string()
});

export const appCallSchema = z.object({
	path: z.string(),
	expand: appExpandSchema.optional(),
	state: z.any().optional()
});

export const appCallRequestSchema = appCallSchema.extend({
	context: appContextSchema,
	values: z.any().optional(),
	raw_command: z.string().optional(),
	selected_field: z.string().optional(),
	query: z.string().optional()
});

export const appLocationSchema = z.enum(AppLocation);

export const productIdentifierSchema = z.string().nullable();

export const productScopeSchema = z.union([
	productIdentifierSchema,
	z.array(productIdentifierSchema)
]);

export const appFormResponseDataSchema = z.object({
	errors: z.record(z.string(), z.string()).optional()
});

export const appFormFieldTypeSchema = z.enum(AppFormFieldType);

export const appFormFieldTextSubTypeSchema = z.enum(AppFormFieldTextSubType);

const multiselectSchema = z.object({
	multiselect: z
		.boolean()
		.optional()
		.describe("Whether a select field allows multiple values to be selected.")
});

const refreshSchema = z.object({
	refresh: z
		.boolean()
		.optional()
		.describe(
			"Allows the form to be refreshed when the value of the field has changed."
		)
});

const lookupSchema = z.object({
	lookup: appCallSchema.describe(
		"A call that returns a list of options for dynamic select fields."
	)
});

const textSubTypeSchema = z.object({
	subtype: appFormFieldTextSubTypeSchema
		.optional()
		.describe("The subtype of text field that will be shown.")
});

const appFormFieldBaseSchema = z.object({
	type: appFormFieldTypeSchema.describe("The type of the field."),
	name: z
		.string()
		.describe(
			"Key to use in the values field of the call.\nCannot include spaces or tabs."
		),
	label: z
		.string()
		.optional()
		.describe(
			"The label of the flag parameter; used with autocomplete.\nIgnored for positional parameters."
		),
	modal_label: z
		.string()
		.optional()
		.describe(
			"Label of the field in modal dialogs.\nDefaults to label if not defined."
		),
	description: z
		.string()
		.optional()
		.describe(
			"Short description of the field, displayed beneath the field in modal dialogs"
		),
	hint: z
		.string()
		.optional()
		.describe("The hint text for the field; used with autocomplete."),
	value: z.unknown().optional().describe("The field's default value."),
	is_required: z
		.boolean()
		.optional()
		.describe("Whether the field has a mandatory value."),
	readonly: z
		.boolean()
		.optional()
		.describe("Whether a field's value is read-only."),
	position: z
		.number()
		.optional()
		.describe(
			"The index of the positional argument.\nA value greater than zero indicates the position this field is in.\nA value of -1 indicates the last argument."
		)
});

export const appFormBooleanFieldSchema = appFormFieldBaseSchema.extend({
	type: z.literal(AppFormFieldType.BOOLEAN)
});

export const appFormMarkdownFieldSchema = appFormFieldBaseSchema.extend({
	type: z.literal(AppFormFieldType.MARKDOWN)
});

export const appFormChannelsFieldSchema = appFormFieldBaseSchema
	.extend(multiselectSchema.shape)
	.extend(refreshSchema.shape)
	.extend({
		type: z.literal(AppFormFieldType.CHANNEL)
	});

export const appFormUsersFieldSchema = appFormFieldBaseSchema
	.extend(multiselectSchema.shape)
	.extend(refreshSchema.shape)
	.extend({
		type: z.literal(AppFormFieldType.USER)
	});

export const appFormDynamicSelectFieldSchema = appFormFieldBaseSchema
	.extend(multiselectSchema.shape)
	.extend(lookupSchema.shape)
	.extend(refreshSchema.shape)
	.extend({
		type: z.literal(AppFormFieldType.DYNAMIC_SELECT)
	});

const optionSchema = z.any();

const optionsSchema = z.any();

const minMaxLentghSchema = z.any();

export const appFormValuesSchema = z.record(
	z.string(),
	z.union([z.string(), optionSchema, z.boolean()]).nullable()
);

export const appFormLookupResponseSchema = z.object({
	items: z.array(optionSchema)
});

export const appFormStaticSelectFieldSchema = appFormFieldBaseSchema
	.extend(multiselectSchema.shape)
	.extend(optionsSchema.shape)
	.extend(refreshSchema.shape)
	.extend({
		type: z.literal(AppFormFieldType.STATIC_SELECT)
	});

export const appFormTextFieldSchema = appFormFieldBaseSchema
	.extend(textSubTypeSchema.shape)
	.extend(minMaxLentghSchema.shape)
	.extend({
		type: z.literal(AppFormFieldType.TEXT)
	});

export const appFormFieldSchema = z.union([
	appFormBooleanFieldSchema,
	appFormChannelsFieldSchema,
	appFormDynamicSelectFieldSchema,
	appFormMarkdownFieldSchema,
	appFormStaticSelectFieldSchema,
	appFormUsersFieldSchema,
	appFormTextFieldSchema
]);

export const appFormSchema = z.object({
	title: z.string().optional(),
	header: z.string().optional(),
	footer: z.string().optional(),
	icon: z.string().optional(),
	submit_buttons: z.string().optional(),
	cancel_button: z.boolean().optional(),
	submit_on_cancel: z.boolean().optional(),
	fields: z.array(appFormFieldSchema).optional(),
	source: appCallSchema.optional(),
	submit: appCallSchema.optional(),
	depends_on: z.array(z.string()).optional()
});

export const appBindingSchema: z.ZodSchema<AppBinding> = z.lazy(() =>
	z.object({
		app_id: z.string(),
		location: z.union([appLocationSchema, z.string()]).optional(),
		supported_product_ids: productScopeSchema.optional(),
		icon: z.string().optional(),
		label: z.string().optional(),
		hint: z.string().optional(),
		description: z.string().optional(),
		role_id: z.string().optional(),
		depends_on_team: z.boolean().optional(),
		depends_on_channel: z.boolean().optional(),
		depends_on_user: z.boolean().optional(),
		depends_on_post: z.boolean().optional(),
		bindings: z.array(appBindingSchema).optional(),
		form: appFormSchema.optional(),
		submit: appCallSchema.optional()
	})
);

export const appCallResponseSchema = z.object({
	type: z.string(),
	text: z.string().optional(),
	data: z.any().optional(),
	navigate_to_url: z.string().optional(),
	use_external_browser: z.boolean().optional(),
	call: appCallSchema.optional(),
	form: appFormSchema.optional(),
	app_metadata: appCallMetadataForClientSchema.optional()
});
