// Generated by ts-to-zod
import { z } from "zod";

export const auditSchema = z.object({
	id: z.string(),
	create_at: z.number(),
	user_id: z.string(),
	action: z.string(),
	extra_info: z.string(),
	ip_address: z.string(),
	session_id: z.string()
});

export const autocompleteSuggestionSchema = z.object({
	Complete: z.string(),
	Suggestion: z.string(),
	Hint: z.string(),
	Description: z.string(),
	IconData: z.string()
});

export const botSchema = z.object({
	user_id: z.string(),
	username: z.string(),
	display_name: z.string().optional(),
	description: z.string().optional(),
	owner_id: z.string(),
	create_at: z.number(),
	update_at: z.number(),
	delete_at: z.number()
});

export const completeOnboardingRequestSchema = z.object({
	organization: z.string(),
	install_plugins: z.array(z.string())
});

export const complianceReportSchema = z.object({
	id: z.string(),
	create_at: z.number(),
	user_id: z.string(),
	status: z.string(),
	count: z.number(),
	desc: z.string(),
	type: z.string(),
	start_at: z.number(),
	end_at: z.number(),
	keywords: z.string(),
	emails: z.string()
});

export const dataRetentionCustomPolicySchema = z.object({
	id: z.string(),
	display_name: z.string(),
	post_duration: z.number(),
	team_count: z.number(),
	channel_count: z.number()
});

export const dataRetentionCustomPoliciesSchema = z.record(
	z.string(),
	dataRetentionCustomPolicySchema
);

export const mfaSecretSchema = z.object({
	secret: z.string(),
	qr_code: z.string()
});

export const preferenceSchema = z.object({
	user_id: z.string(),
	category: z.string(),
	name: z.string(),
	value: z.string()
});

export const productNoticeSchema = z.object({
	id: z.string(),
	title: z.string(),
	description: z.string(),
	image: z.string().optional(),
	actionText: z.string().optional(),
	action: z.union([z.literal("url"), z.literal("")]).optional(),
	actionParam: z.string().optional(),
	sysAdminOnly: z.boolean(),
	teamAdminOnly: z.boolean()
});

export const reactionSchema = z.object({
	user_id: z.string(),
	post_id: z.string(),
	emoji_name: z.string(),
	create_at: z.number()
});

export const samlCertificateStatusSchema = z.object({
	idp_certificate_file: z.string(),
	private_key_file: z.string(),
	public_certificate_file: z.string()
});

export const samlMetadataResponseSchema = z.object({
	idp_descriptor_url: z.string(),
	idp_url: z.string(),
	idp_public_certificate: z.string()
});

export const serverLimitsSchema = z.object({
	activeUserCount: z.number(),
	maxUsersLimit: z.number()
});

export const schemeSchema = z.object({
	id: z.string(),
	name: z.string(),
	description: z.string(),
	display_name: z.string(),
	create_at: z.number(),
	update_at: z.number(),
	delete_at: z.number(),
	scope: z.union([z.literal("team"), z.literal("channel")]),
	default_team_admin_role: z.string(),
	default_team_user_role: z.string(),
	default_team_guest_role: z.string(),
	default_channel_admin_role: z.string(),
	default_channel_user_role: z.string(),
	default_channel_guest_role: z.string(),
	default_playbook_admin_role: z.string(),
	default_playbook_member_role: z.string(),
	default_run_member_role: z.string()
});

export const searchSchema = z.object({
	terms: z.string(),
	isOrSearch: z.boolean()
});

export const searchParameterSchema = z.object({
	terms: z.string(),
	is_or_search: z.boolean(),
	time_zone_offset: z.number().optional(),
	page: z.number(),
	per_page: z.number(),
	include_deleted_channels: z.boolean()
});

export const termsOfServiceSchema = z.object({
	id: z.string(),
	create_at: z.number(),
	user_id: z.string(),
	text: z.string()
});

export const typingSchema = z.record(
	z.string(),
	z.record(z.string(), z.number())
);

const userProfileSchema = z.any();

const postMetadataSchema = z.any();

const postPriorityMetadataSchema = z.any();

export const autocompleteUserSchema = z.object({
	users: z.array(userProfileSchema),
	out_of_channel: z.array(userProfileSchema).optional()
});

export const draftSchema = z.object({
	create_at: z.number(),
	update_at: z.number(),
	delete_at: z.number(),
	user_id: z.string(),
	channel_id: z.string(),
	root_id: z.string(),
	message: z.string(),
	props: z.record(z.string(), z.unknown()),
	file_ids: z.array(z.string()).optional(),
	metadata: postMetadataSchema.optional(),
	priority: postPriorityMetadataSchema.optional()
});
